// Code generated by Fern. DO NOT EDIT.

package botdetection

import (
	context "context"

	management "github.com/auth0/go-auth0/v3/management"
	core "github.com/auth0/go-auth0/v3/management/core"
	internal "github.com/auth0/go-auth0/v3/management/internal"
	option "github.com/auth0/go-auth0/v3/management/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Get the Bot Detection configuration of your tenant.
//
// Example:
//
//	client.AttackProtection.BotDetection.Get(
//	    context.TODO(),
//	)
func (c *Client) Get(
	ctx context.Context,
	opts ...option.RequestOption,
) (*management.GetBotDetectionSettingsResponseContent, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update the Bot Detection configuration of your tenant.
//
// Example:
//
//	request := &management.UpdateBotDetectionSettingsRequestContent{}
//	client.AttackProtection.BotDetection.Update(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Update(
	ctx context.Context,
	request *management.UpdateBotDetectionSettingsRequestContent,
	opts ...option.RequestOption,
) (*management.UpdateBotDetectionSettingsResponseContent, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
