version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - gocyclo
    - godot
    - gosec
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
    - dupword
    - fatcontext
    - govet
    - misspell
    - wsl_v5
  settings:
    godot:
      scope: declarations
      capital: true
    staticcheck:
      checks:
        - all
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        path: (.+)_test.go
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/auth0/go-auth0
  exclusions:
    generated: lax
