/*
Auth0 Management API

Auth0 Management API v2.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// ConnectionCreateOptionsAttributesEmailSignupVerification struct for ConnectionCreateOptionsAttributesEmailSignupVerification
type ConnectionCreateOptionsAttributesEmailSignupVerification struct {
	Active *bool `json:"active,omitempty"`
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *ConnectionCreateOptionsAttributesEmailSignupVerification) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionCreateOptionsAttributesEmailSignupVerification) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *ConnectionCreateOptionsAttributesEmailSignupVerification) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *ConnectionCreateOptionsAttributesEmailSignupVerification) SetActive(v bool) {
	o.Active = &v
}

func (o ConnectionCreateOptionsAttributesEmailSignupVerification) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionCreateOptionsAttributesEmailSignupVerification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	return toSerialize, nil
}

type NullableConnectionCreateOptionsAttributesEmailSignupVerification struct {
	value *ConnectionCreateOptionsAttributesEmailSignupVerification
	isSet bool
}

func (v NullableConnectionCreateOptionsAttributesEmailSignupVerification) Get() *ConnectionCreateOptionsAttributesEmailSignupVerification {
	return v.value
}

func (v *NullableConnectionCreateOptionsAttributesEmailSignupVerification) Set(val *ConnectionCreateOptionsAttributesEmailSignupVerification) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionCreateOptionsAttributesEmailSignupVerification) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionCreateOptionsAttributesEmailSignupVerification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionCreateOptionsAttributesEmailSignupVerification(val *ConnectionCreateOptionsAttributesEmailSignupVerification) *NullableConnectionCreateOptionsAttributesEmailSignupVerification {
	return &NullableConnectionCreateOptionsAttributesEmailSignupVerification{value: val, isSet: true}
}

func (v NullableConnectionCreateOptionsAttributesEmailSignupVerification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionCreateOptionsAttributesEmailSignupVerification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
