/*
Auth0 Management API

Auth0 Management API v2.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"

	"gopkg.in/validator.v2"
)

// GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt - struct for GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt
type GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt struct {
	MapmapOfStringAny *map[string]interface{}
	TimeTime          *time.Time
}

// map[string]interface{}AsGetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt is a convenience function that returns map[string]interface{} wrapped in GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt
func MapmapOfStringAnyAsGetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt(v *map[string]interface{}) GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt {
	return GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt{
		MapmapOfStringAny: v,
	}
}

// time.TimeAsGetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt is a convenience function that returns time.Time wrapped in GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt
func TimeTimeAsGetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt(v *time.Time) GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt {
	return GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt{
		TimeTime: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	// try to unmarshal data into TimeTime
	err = newStrictDecoder(data).Decode(&dst.TimeTime)
	if err == nil {
		jsonTimeTime, _ := json.Marshal(dst.TimeTime)
		if string(jsonTimeTime) == "{}" { // empty struct
			dst.TimeTime = nil
		} else {
			if err = validator.Validate(dst.TimeTime); err != nil {
				dst.TimeTime = nil
			} else {
				match++
			}
		}
	} else {
		dst.TimeTime = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.MapmapOfStringAny = nil
		dst.TimeTime = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt) MarshalJSON() ([]byte, error) {
	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	if src.TimeTime != nil {
		return json.Marshal(&src.TimeTime)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	if obj.TimeTime != nil {
		return obj.TimeTime
	}

	// all schemas are nil
	return nil
}

type NullableGetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt struct {
	value *GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt
	isSet bool
}

func (v NullableGetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt) Get() *GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt {
	return v.value
}

func (v *NullableGetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt) Set(val *GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt(val *GetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt) *NullableGetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt {
	return &NullableGetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt{value: val, isSet: true}
}

func (v NullableGetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRefreshTokensForUser200ResponseSessionsInnerIdleExpiresAt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
