/*
Auth0 Management API

Auth0 Management API v2.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
)

// GetActions200ResponseActionsInner struct for GetActions200ResponseActionsInner
type GetActions200ResponseActionsInner struct {
	// The unique ID of the action.
	Id string `json:"id"`
	// The name of an action.
	Name string `json:"name"`
	// The list of triggers that this action supports. At this time, an action can only target a single trigger at a time.
	SupportedTriggers []GetActions200ResponseActionsInnerSupportedTriggersInner `json:"supported_triggers"`
	// The source code of the action.
	Code string `json:"code"`
	// The list of third party npm modules, and their versions, that this action depends on.
	Dependencies []GetActions200ResponseActionsInnerDependenciesInner `json:"dependencies"`
	// The Node runtime. For example: `node12`, defaults to `node12`
	Runtime string `json:"runtime"`
	// The list of secrets that are included in an action or a version of an action.
	Secrets []GetActions200ResponseActionsInnerSecretsInner `json:"secrets"`
	// The version of the action that is currently deployed.
	DeployedVersion map[string]interface{} `json:"deployed_version"`
	// installed_integration_id is the fk reference to the InstalledIntegration entity.
	InstalledIntegrationId string                                       `json:"installed_integration_id"`
	Integration            GetActions200ResponseActionsInnerIntegration `json:"integration"`
	Status                 GetActions200ResponseActionsInnerStatus      `json:"status"`
	// True if all of an Action's contents have been deployed.
	AllChangesDeployed bool `json:"all_changes_deployed"`
	// The time when this action was built successfully.
	BuiltAt string `json:"built_at"`
	// The time when this action was created.
	CreatedAt string `json:"created_at"`
	// The time when this action was updated.
	UpdatedAt string `json:"updated_at"`
}

type _GetActions200ResponseActionsInner GetActions200ResponseActionsInner

// GetId returns the Id field value
func (o *GetActions200ResponseActionsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetActions200ResponseActionsInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GetActions200ResponseActionsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetActions200ResponseActionsInner) SetName(v string) {
	o.Name = v
}

// GetSupportedTriggers returns the SupportedTriggers field value
func (o *GetActions200ResponseActionsInner) GetSupportedTriggers() []GetActions200ResponseActionsInnerSupportedTriggersInner {
	if o == nil {
		var ret []GetActions200ResponseActionsInnerSupportedTriggersInner
		return ret
	}

	return o.SupportedTriggers
}

// GetSupportedTriggersOk returns a tuple with the SupportedTriggers field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInner) GetSupportedTriggersOk() ([]GetActions200ResponseActionsInnerSupportedTriggersInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupportedTriggers, true
}

// SetSupportedTriggers sets field value
func (o *GetActions200ResponseActionsInner) SetSupportedTriggers(v []GetActions200ResponseActionsInnerSupportedTriggersInner) {
	o.SupportedTriggers = v
}

// GetCode returns the Code field value
func (o *GetActions200ResponseActionsInner) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInner) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GetActions200ResponseActionsInner) SetCode(v string) {
	o.Code = v
}

// GetDependencies returns the Dependencies field value
func (o *GetActions200ResponseActionsInner) GetDependencies() []GetActions200ResponseActionsInnerDependenciesInner {
	if o == nil {
		var ret []GetActions200ResponseActionsInnerDependenciesInner
		return ret
	}

	return o.Dependencies
}

// GetDependenciesOk returns a tuple with the Dependencies field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInner) GetDependenciesOk() ([]GetActions200ResponseActionsInnerDependenciesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dependencies, true
}

// SetDependencies sets field value
func (o *GetActions200ResponseActionsInner) SetDependencies(v []GetActions200ResponseActionsInnerDependenciesInner) {
	o.Dependencies = v
}

// GetRuntime returns the Runtime field value
func (o *GetActions200ResponseActionsInner) GetRuntime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Runtime
}

// GetRuntimeOk returns a tuple with the Runtime field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInner) GetRuntimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Runtime, true
}

// SetRuntime sets field value
func (o *GetActions200ResponseActionsInner) SetRuntime(v string) {
	o.Runtime = v
}

// GetSecrets returns the Secrets field value
func (o *GetActions200ResponseActionsInner) GetSecrets() []GetActions200ResponseActionsInnerSecretsInner {
	if o == nil {
		var ret []GetActions200ResponseActionsInnerSecretsInner
		return ret
	}

	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInner) GetSecretsOk() ([]GetActions200ResponseActionsInnerSecretsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Secrets, true
}

// SetSecrets sets field value
func (o *GetActions200ResponseActionsInner) SetSecrets(v []GetActions200ResponseActionsInnerSecretsInner) {
	o.Secrets = v
}

// GetDeployedVersion returns the DeployedVersion field value
func (o *GetActions200ResponseActionsInner) GetDeployedVersion() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.DeployedVersion
}

// GetDeployedVersionOk returns a tuple with the DeployedVersion field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInner) GetDeployedVersionOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.DeployedVersion, true
}

// SetDeployedVersion sets field value
func (o *GetActions200ResponseActionsInner) SetDeployedVersion(v map[string]interface{}) {
	o.DeployedVersion = v
}

// GetInstalledIntegrationId returns the InstalledIntegrationId field value
func (o *GetActions200ResponseActionsInner) GetInstalledIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstalledIntegrationId
}

// GetInstalledIntegrationIdOk returns a tuple with the InstalledIntegrationId field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInner) GetInstalledIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstalledIntegrationId, true
}

// SetInstalledIntegrationId sets field value
func (o *GetActions200ResponseActionsInner) SetInstalledIntegrationId(v string) {
	o.InstalledIntegrationId = v
}

// GetIntegration returns the Integration field value
func (o *GetActions200ResponseActionsInner) GetIntegration() GetActions200ResponseActionsInnerIntegration {
	if o == nil {
		var ret GetActions200ResponseActionsInnerIntegration
		return ret
	}

	return o.Integration
}

// GetIntegrationOk returns a tuple with the Integration field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInner) GetIntegrationOk() (*GetActions200ResponseActionsInnerIntegration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Integration, true
}

// SetIntegration sets field value
func (o *GetActions200ResponseActionsInner) SetIntegration(v GetActions200ResponseActionsInnerIntegration) {
	o.Integration = v
}

// GetStatus returns the Status field value
func (o *GetActions200ResponseActionsInner) GetStatus() GetActions200ResponseActionsInnerStatus {
	if o == nil {
		var ret GetActions200ResponseActionsInnerStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInner) GetStatusOk() (*GetActions200ResponseActionsInnerStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetActions200ResponseActionsInner) SetStatus(v GetActions200ResponseActionsInnerStatus) {
	o.Status = v
}

// GetAllChangesDeployed returns the AllChangesDeployed field value
func (o *GetActions200ResponseActionsInner) GetAllChangesDeployed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AllChangesDeployed
}

// GetAllChangesDeployedOk returns a tuple with the AllChangesDeployed field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInner) GetAllChangesDeployedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllChangesDeployed, true
}

// SetAllChangesDeployed sets field value
func (o *GetActions200ResponseActionsInner) SetAllChangesDeployed(v bool) {
	o.AllChangesDeployed = v
}

// GetBuiltAt returns the BuiltAt field value
func (o *GetActions200ResponseActionsInner) GetBuiltAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BuiltAt
}

// GetBuiltAtOk returns a tuple with the BuiltAt field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInner) GetBuiltAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuiltAt, true
}

// SetBuiltAt sets field value
func (o *GetActions200ResponseActionsInner) SetBuiltAt(v string) {
	o.BuiltAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetActions200ResponseActionsInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetActions200ResponseActionsInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GetActions200ResponseActionsInner) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GetActions200ResponseActionsInner) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o GetActions200ResponseActionsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetActions200ResponseActionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["supported_triggers"] = o.SupportedTriggers
	toSerialize["code"] = o.Code
	toSerialize["dependencies"] = o.Dependencies
	toSerialize["runtime"] = o.Runtime
	toSerialize["secrets"] = o.Secrets
	toSerialize["deployed_version"] = o.DeployedVersion
	toSerialize["installed_integration_id"] = o.InstalledIntegrationId
	toSerialize["integration"] = o.Integration
	toSerialize["status"] = o.Status
	toSerialize["all_changes_deployed"] = o.AllChangesDeployed
	toSerialize["built_at"] = o.BuiltAt
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *GetActions200ResponseActionsInner) UnmarshalJSON(data []byte) (err error) {
	varGetActions200ResponseActionsInner := _GetActions200ResponseActionsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetActions200ResponseActionsInner)

	if err != nil {
		return err
	}

	*o = GetActions200ResponseActionsInner(varGetActions200ResponseActionsInner)

	return err
}

type NullableGetActions200ResponseActionsInner struct {
	value *GetActions200ResponseActionsInner
	isSet bool
}

func (v NullableGetActions200ResponseActionsInner) Get() *GetActions200ResponseActionsInner {
	return v.value
}

func (v *NullableGetActions200ResponseActionsInner) Set(val *GetActions200ResponseActionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetActions200ResponseActionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetActions200ResponseActionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetActions200ResponseActionsInner(val *GetActions200ResponseActionsInner) *NullableGetActions200ResponseActionsInner {
	return &NullableGetActions200ResponseActionsInner{value: val, isSet: true}
}

func (v NullableGetActions200ResponseActionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetActions200ResponseActionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
