/*
Auth0 Management API

Auth0 Management API v2.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// GetActions200ResponseActionsInnerIntegrationCurrentRelease struct for GetActions200ResponseActionsInnerIntegrationCurrentRelease
type GetActions200ResponseActionsInnerIntegrationCurrentRelease struct {
	// The id of the associated IntegrationRelease
	Id      string                                                           `json:"id"`
	Trigger GetActions200ResponseActionsInnerSupportedTriggersInner          `json:"trigger"`
	Semver  GetActions200ResponseActionsInnerIntegrationCurrentReleaseSemver `json:"semver"`
	// required_secrets declares all the necessary secrets for an integration to work.
	RequiredSecrets []GetActions200ResponseActionsInnerIntegrationCurrentReleaseRequiredSecretsInner `json:"required_secrets"`
	// required_configuration declares all the necessary configuration fields for an integration to work.
	RequiredConfiguration []GetActions200ResponseActionsInnerIntegrationCurrentReleaseRequiredSecretsInner `json:"required_configuration"`
	AdditionalProperties  map[string]interface{}
}

type _GetActions200ResponseActionsInnerIntegrationCurrentRelease GetActions200ResponseActionsInnerIntegrationCurrentRelease

// GetId returns the Id field value
func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) SetId(v string) {
	o.Id = v
}

// GetTrigger returns the Trigger field value
func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) GetTrigger() GetActions200ResponseActionsInnerSupportedTriggersInner {
	if o == nil {
		var ret GetActions200ResponseActionsInnerSupportedTriggersInner
		return ret
	}

	return o.Trigger
}

// GetTriggerOk returns a tuple with the Trigger field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) GetTriggerOk() (*GetActions200ResponseActionsInnerSupportedTriggersInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Trigger, true
}

// SetTrigger sets field value
func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) SetTrigger(v GetActions200ResponseActionsInnerSupportedTriggersInner) {
	o.Trigger = v
}

// GetSemver returns the Semver field value
func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) GetSemver() GetActions200ResponseActionsInnerIntegrationCurrentReleaseSemver {
	if o == nil {
		var ret GetActions200ResponseActionsInnerIntegrationCurrentReleaseSemver
		return ret
	}

	return o.Semver
}

// GetSemverOk returns a tuple with the Semver field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) GetSemverOk() (*GetActions200ResponseActionsInnerIntegrationCurrentReleaseSemver, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Semver, true
}

// SetSemver sets field value
func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) SetSemver(v GetActions200ResponseActionsInnerIntegrationCurrentReleaseSemver) {
	o.Semver = v
}

// GetRequiredSecrets returns the RequiredSecrets field value
func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) GetRequiredSecrets() []GetActions200ResponseActionsInnerIntegrationCurrentReleaseRequiredSecretsInner {
	if o == nil {
		var ret []GetActions200ResponseActionsInnerIntegrationCurrentReleaseRequiredSecretsInner
		return ret
	}

	return o.RequiredSecrets
}

// GetRequiredSecretsOk returns a tuple with the RequiredSecrets field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) GetRequiredSecretsOk() ([]GetActions200ResponseActionsInnerIntegrationCurrentReleaseRequiredSecretsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequiredSecrets, true
}

// SetRequiredSecrets sets field value
func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) SetRequiredSecrets(v []GetActions200ResponseActionsInnerIntegrationCurrentReleaseRequiredSecretsInner) {
	o.RequiredSecrets = v
}

// GetRequiredConfiguration returns the RequiredConfiguration field value
func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) GetRequiredConfiguration() []GetActions200ResponseActionsInnerIntegrationCurrentReleaseRequiredSecretsInner {
	if o == nil {
		var ret []GetActions200ResponseActionsInnerIntegrationCurrentReleaseRequiredSecretsInner
		return ret
	}

	return o.RequiredConfiguration
}

// GetRequiredConfigurationOk returns a tuple with the RequiredConfiguration field value
// and a boolean to check if the value has been set.
func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) GetRequiredConfigurationOk() ([]GetActions200ResponseActionsInnerIntegrationCurrentReleaseRequiredSecretsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequiredConfiguration, true
}

// SetRequiredConfiguration sets field value
func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) SetRequiredConfiguration(v []GetActions200ResponseActionsInnerIntegrationCurrentReleaseRequiredSecretsInner) {
	o.RequiredConfiguration = v
}

func (o GetActions200ResponseActionsInnerIntegrationCurrentRelease) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetActions200ResponseActionsInnerIntegrationCurrentRelease) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["trigger"] = o.Trigger
	toSerialize["semver"] = o.Semver
	toSerialize["required_secrets"] = o.RequiredSecrets
	toSerialize["required_configuration"] = o.RequiredConfiguration

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetActions200ResponseActionsInnerIntegrationCurrentRelease) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"trigger",
		"semver",
		"required_secrets",
		"required_configuration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetActions200ResponseActionsInnerIntegrationCurrentRelease := _GetActions200ResponseActionsInnerIntegrationCurrentRelease{}

	err = json.Unmarshal(data, &varGetActions200ResponseActionsInnerIntegrationCurrentRelease)

	if err != nil {
		return err
	}

	*o = GetActions200ResponseActionsInnerIntegrationCurrentRelease(varGetActions200ResponseActionsInnerIntegrationCurrentRelease)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "trigger")
		delete(additionalProperties, "semver")
		delete(additionalProperties, "required_secrets")
		delete(additionalProperties, "required_configuration")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetActions200ResponseActionsInnerIntegrationCurrentRelease struct {
	value *GetActions200ResponseActionsInnerIntegrationCurrentRelease
	isSet bool
}

func (v NullableGetActions200ResponseActionsInnerIntegrationCurrentRelease) Get() *GetActions200ResponseActionsInnerIntegrationCurrentRelease {
	return v.value
}

func (v *NullableGetActions200ResponseActionsInnerIntegrationCurrentRelease) Set(val *GetActions200ResponseActionsInnerIntegrationCurrentRelease) {
	v.value = val
	v.isSet = true
}

func (v NullableGetActions200ResponseActionsInnerIntegrationCurrentRelease) IsSet() bool {
	return v.isSet
}

func (v *NullableGetActions200ResponseActionsInnerIntegrationCurrentRelease) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetActions200ResponseActionsInnerIntegrationCurrentRelease(val *GetActions200ResponseActionsInnerIntegrationCurrentRelease) *NullableGetActions200ResponseActionsInnerIntegrationCurrentRelease {
	return &NullableGetActions200ResponseActionsInnerIntegrationCurrentRelease{value: val, isSet: true}
}

func (v NullableGetActions200ResponseActionsInnerIntegrationCurrentRelease) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetActions200ResponseActionsInnerIntegrationCurrentRelease) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
