/*
Auth0 Management API

Auth0 Management API v2.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// PatchOrganizationsByIdRequestBranding Theme defines how to style the login pages
type PatchOrganizationsByIdRequestBranding struct {
	// URL of logo to display on login page
	LogoUrl *string                                              `json:"logo_url,omitempty"`
	Colors  *GetOrganizations200ResponseOneOfInnerBrandingColors `json:"colors,omitempty"`
}

// GetLogoUrl returns the LogoUrl field value if set, zero value otherwise.
func (o *PatchOrganizationsByIdRequestBranding) GetLogoUrl() string {
	if o == nil || IsNil(o.LogoUrl) {
		var ret string
		return ret
	}
	return *o.LogoUrl
}

// GetLogoUrlOk returns a tuple with the LogoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchOrganizationsByIdRequestBranding) GetLogoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.LogoUrl) {
		return nil, false
	}
	return o.LogoUrl, true
}

// HasLogoUrl returns a boolean if a field has been set.
func (o *PatchOrganizationsByIdRequestBranding) HasLogoUrl() bool {
	if o != nil && !IsNil(o.LogoUrl) {
		return true
	}

	return false
}

// SetLogoUrl gets a reference to the given string and assigns it to the LogoUrl field.
func (o *PatchOrganizationsByIdRequestBranding) SetLogoUrl(v string) {
	o.LogoUrl = &v
}

// GetColors returns the Colors field value if set, zero value otherwise.
func (o *PatchOrganizationsByIdRequestBranding) GetColors() GetOrganizations200ResponseOneOfInnerBrandingColors {
	if o == nil || IsNil(o.Colors) {
		var ret GetOrganizations200ResponseOneOfInnerBrandingColors
		return ret
	}
	return *o.Colors
}

// GetColorsOk returns a tuple with the Colors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchOrganizationsByIdRequestBranding) GetColorsOk() (*GetOrganizations200ResponseOneOfInnerBrandingColors, bool) {
	if o == nil || IsNil(o.Colors) {
		return nil, false
	}
	return o.Colors, true
}

// HasColors returns a boolean if a field has been set.
func (o *PatchOrganizationsByIdRequestBranding) HasColors() bool {
	if o != nil && !IsNil(o.Colors) {
		return true
	}

	return false
}

// SetColors gets a reference to the given GetOrganizations200ResponseOneOfInnerBrandingColors and assigns it to the Colors field.
func (o *PatchOrganizationsByIdRequestBranding) SetColors(v GetOrganizations200ResponseOneOfInnerBrandingColors) {
	o.Colors = &v
}

func (o PatchOrganizationsByIdRequestBranding) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchOrganizationsByIdRequestBranding) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LogoUrl) {
		toSerialize["logo_url"] = o.LogoUrl
	}
	if !IsNil(o.Colors) {
		toSerialize["colors"] = o.Colors
	}
	return toSerialize, nil
}

type NullablePatchOrganizationsByIdRequestBranding struct {
	value *PatchOrganizationsByIdRequestBranding
	isSet bool
}

func (v NullablePatchOrganizationsByIdRequestBranding) Get() *PatchOrganizationsByIdRequestBranding {
	return v.value
}

func (v *NullablePatchOrganizationsByIdRequestBranding) Set(val *PatchOrganizationsByIdRequestBranding) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchOrganizationsByIdRequestBranding) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchOrganizationsByIdRequestBranding) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchOrganizationsByIdRequestBranding(val *PatchOrganizationsByIdRequestBranding) *NullablePatchOrganizationsByIdRequestBranding {
	return &NullablePatchOrganizationsByIdRequestBranding{value: val, isSet: true}
}

func (v NullablePatchOrganizationsByIdRequestBranding) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchOrganizationsByIdRequestBranding) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
