/*
Auth0 Management API

Auth0 Management API v2.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// PostActionRequestSecretsInner struct for PostActionRequestSecretsInner
type PostActionRequestSecretsInner struct {
	// The name of the particular secret, e.g. API_KEY.
	Name *string `json:"name,omitempty"`
	// The value of the particular secret, e.g. secret123. A secret's value can only be set upon creation. A secret's value will never be returned by the API.
	Value                *string `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PostActionRequestSecretsInner PostActionRequestSecretsInner

// GetName returns the Name field value if set, zero value otherwise.
func (o *PostActionRequestSecretsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostActionRequestSecretsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PostActionRequestSecretsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PostActionRequestSecretsInner) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *PostActionRequestSecretsInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostActionRequestSecretsInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *PostActionRequestSecretsInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *PostActionRequestSecretsInner) SetValue(v string) {
	o.Value = &v
}

func (o PostActionRequestSecretsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostActionRequestSecretsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PostActionRequestSecretsInner) UnmarshalJSON(data []byte) (err error) {
	varPostActionRequestSecretsInner := _PostActionRequestSecretsInner{}

	err = json.Unmarshal(data, &varPostActionRequestSecretsInner)

	if err != nil {
		return err
	}

	*o = PostActionRequestSecretsInner(varPostActionRequestSecretsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePostActionRequestSecretsInner struct {
	value *PostActionRequestSecretsInner
	isSet bool
}

func (v NullablePostActionRequestSecretsInner) Get() *PostActionRequestSecretsInner {
	return v.value
}

func (v *NullablePostActionRequestSecretsInner) Set(val *PostActionRequestSecretsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePostActionRequestSecretsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePostActionRequestSecretsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostActionRequestSecretsInner(val *PostActionRequestSecretsInner) *NullablePostActionRequestSecretsInner {
	return &NullablePostActionRequestSecretsInner{value: val, isSet: true}
}

func (v NullablePostActionRequestSecretsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostActionRequestSecretsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
