/*
Auth0 Management API

Auth0 Management API v2.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
)

// PostBrandingTheme200Response struct for PostBrandingTheme200Response
type PostBrandingTheme200Response struct {
	Borders PostBrandingThemeRequestBorders `json:"borders"`
	Colors  PostBrandingThemeRequestColors  `json:"colors"`
	// Display Name
	DisplayName    string                                 `json:"displayName"`
	Fonts          PostBrandingThemeRequestFonts          `json:"fonts"`
	PageBackground PostBrandingThemeRequestPageBackground `json:"page_background"`
	// Theme Id
	ThemeId string                         `json:"themeId"`
	Widget  PostBrandingThemeRequestWidget `json:"widget"`
}

type _PostBrandingTheme200Response PostBrandingTheme200Response

// GetBorders returns the Borders field value
func (o *PostBrandingTheme200Response) GetBorders() PostBrandingThemeRequestBorders {
	if o == nil {
		var ret PostBrandingThemeRequestBorders
		return ret
	}

	return o.Borders
}

// GetBordersOk returns a tuple with the Borders field value
// and a boolean to check if the value has been set.
func (o *PostBrandingTheme200Response) GetBordersOk() (*PostBrandingThemeRequestBorders, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Borders, true
}

// SetBorders sets field value
func (o *PostBrandingTheme200Response) SetBorders(v PostBrandingThemeRequestBorders) {
	o.Borders = v
}

// GetColors returns the Colors field value
func (o *PostBrandingTheme200Response) GetColors() PostBrandingThemeRequestColors {
	if o == nil {
		var ret PostBrandingThemeRequestColors
		return ret
	}

	return o.Colors
}

// GetColorsOk returns a tuple with the Colors field value
// and a boolean to check if the value has been set.
func (o *PostBrandingTheme200Response) GetColorsOk() (*PostBrandingThemeRequestColors, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Colors, true
}

// SetColors sets field value
func (o *PostBrandingTheme200Response) SetColors(v PostBrandingThemeRequestColors) {
	o.Colors = v
}

// GetDisplayName returns the DisplayName field value
func (o *PostBrandingTheme200Response) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *PostBrandingTheme200Response) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *PostBrandingTheme200Response) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetFonts returns the Fonts field value
func (o *PostBrandingTheme200Response) GetFonts() PostBrandingThemeRequestFonts {
	if o == nil {
		var ret PostBrandingThemeRequestFonts
		return ret
	}

	return o.Fonts
}

// GetFontsOk returns a tuple with the Fonts field value
// and a boolean to check if the value has been set.
func (o *PostBrandingTheme200Response) GetFontsOk() (*PostBrandingThemeRequestFonts, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fonts, true
}

// SetFonts sets field value
func (o *PostBrandingTheme200Response) SetFonts(v PostBrandingThemeRequestFonts) {
	o.Fonts = v
}

// GetPageBackground returns the PageBackground field value
func (o *PostBrandingTheme200Response) GetPageBackground() PostBrandingThemeRequestPageBackground {
	if o == nil {
		var ret PostBrandingThemeRequestPageBackground
		return ret
	}

	return o.PageBackground
}

// GetPageBackgroundOk returns a tuple with the PageBackground field value
// and a boolean to check if the value has been set.
func (o *PostBrandingTheme200Response) GetPageBackgroundOk() (*PostBrandingThemeRequestPageBackground, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageBackground, true
}

// SetPageBackground sets field value
func (o *PostBrandingTheme200Response) SetPageBackground(v PostBrandingThemeRequestPageBackground) {
	o.PageBackground = v
}

// GetThemeId returns the ThemeId field value
func (o *PostBrandingTheme200Response) GetThemeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ThemeId
}

// GetThemeIdOk returns a tuple with the ThemeId field value
// and a boolean to check if the value has been set.
func (o *PostBrandingTheme200Response) GetThemeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThemeId, true
}

// SetThemeId sets field value
func (o *PostBrandingTheme200Response) SetThemeId(v string) {
	o.ThemeId = v
}

// GetWidget returns the Widget field value
func (o *PostBrandingTheme200Response) GetWidget() PostBrandingThemeRequestWidget {
	if o == nil {
		var ret PostBrandingThemeRequestWidget
		return ret
	}

	return o.Widget
}

// GetWidgetOk returns a tuple with the Widget field value
// and a boolean to check if the value has been set.
func (o *PostBrandingTheme200Response) GetWidgetOk() (*PostBrandingThemeRequestWidget, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Widget, true
}

// SetWidget sets field value
func (o *PostBrandingTheme200Response) SetWidget(v PostBrandingThemeRequestWidget) {
	o.Widget = v
}

func (o PostBrandingTheme200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostBrandingTheme200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["borders"] = o.Borders
	toSerialize["colors"] = o.Colors
	toSerialize["displayName"] = o.DisplayName
	toSerialize["fonts"] = o.Fonts
	toSerialize["page_background"] = o.PageBackground
	toSerialize["themeId"] = o.ThemeId
	toSerialize["widget"] = o.Widget
	return toSerialize, nil
}

func (o *PostBrandingTheme200Response) UnmarshalJSON(data []byte) (err error) {
	varPostBrandingTheme200Response := _PostBrandingTheme200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostBrandingTheme200Response)

	if err != nil {
		return err
	}

	*o = PostBrandingTheme200Response(varPostBrandingTheme200Response)

	return err
}

type NullablePostBrandingTheme200Response struct {
	value *PostBrandingTheme200Response
	isSet bool
}

func (v NullablePostBrandingTheme200Response) Get() *PostBrandingTheme200Response {
	return v.value
}

func (v *NullablePostBrandingTheme200Response) Set(val *PostBrandingTheme200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostBrandingTheme200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostBrandingTheme200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostBrandingTheme200Response(val *PostBrandingTheme200Response) *NullablePostBrandingTheme200Response {
	return &NullablePostBrandingTheme200Response{value: val, isSet: true}
}

func (v NullablePostBrandingTheme200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostBrandingTheme200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
