/*
Auth0 Management API

Auth0 Management API v2.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// PostCustomDomainsRequestVerificationMethod Custom domain verification method. Must be `txt`.
type PostCustomDomainsRequestVerificationMethod string

// List of post_custom_domains_request_verification_method
const (
	POSTCUSTOMDOMAINSREQUESTVERIFICATIONMETHOD_TXT PostCustomDomainsRequestVerificationMethod = "txt"
)

// All allowed values of PostCustomDomainsRequestVerificationMethod enum
var AllowedPostCustomDomainsRequestVerificationMethodEnumValues = []PostCustomDomainsRequestVerificationMethod{
	"txt",
}

func (v *PostCustomDomainsRequestVerificationMethod) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PostCustomDomainsRequestVerificationMethod(value)
	for _, existing := range AllowedPostCustomDomainsRequestVerificationMethodEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PostCustomDomainsRequestVerificationMethod", value)
}

// NewPostCustomDomainsRequestVerificationMethodFromValue returns a pointer to a valid PostCustomDomainsRequestVerificationMethod
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPostCustomDomainsRequestVerificationMethodFromValue(v string) (*PostCustomDomainsRequestVerificationMethod, error) {
	ev := PostCustomDomainsRequestVerificationMethod(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PostCustomDomainsRequestVerificationMethod: valid values are %v", v, AllowedPostCustomDomainsRequestVerificationMethodEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PostCustomDomainsRequestVerificationMethod) IsValid() bool {
	for _, existing := range AllowedPostCustomDomainsRequestVerificationMethodEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to post_custom_domains_request_verification_method value
func (v PostCustomDomainsRequestVerificationMethod) Ptr() *PostCustomDomainsRequestVerificationMethod {
	return &v
}

type NullablePostCustomDomainsRequestVerificationMethod struct {
	value *PostCustomDomainsRequestVerificationMethod
	isSet bool
}

func (v NullablePostCustomDomainsRequestVerificationMethod) Get() *PostCustomDomainsRequestVerificationMethod {
	return v.value
}

func (v *NullablePostCustomDomainsRequestVerificationMethod) Set(val *PostCustomDomainsRequestVerificationMethod) {
	v.value = val
	v.isSet = true
}

func (v NullablePostCustomDomainsRequestVerificationMethod) IsSet() bool {
	return v.isSet
}

func (v *NullablePostCustomDomainsRequestVerificationMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostCustomDomainsRequestVerificationMethod(val *PostCustomDomainsRequestVerificationMethod) *NullablePostCustomDomainsRequestVerificationMethod {
	return &NullablePostCustomDomainsRequestVerificationMethod{value: val, isSet: true}
}

func (v NullablePostCustomDomainsRequestVerificationMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostCustomDomainsRequestVerificationMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
