/*
Auth0 Management API

Auth0 Management API v2.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// PostPermissionsRequest struct for PostPermissionsRequest
type PostPermissionsRequest struct {
	// List of permissions to add to this user.
	Permissions []PostRolePermissionAssignmentRequestPermissionsInner `json:"permissions"`
}

type _PostPermissionsRequest PostPermissionsRequest

// GetPermissions returns the Permissions field value
func (o *PostPermissionsRequest) GetPermissions() []PostRolePermissionAssignmentRequestPermissionsInner {
	if o == nil {
		var ret []PostRolePermissionAssignmentRequestPermissionsInner
		return ret
	}

	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value
// and a boolean to check if the value has been set.
func (o *PostPermissionsRequest) GetPermissionsOk() ([]PostRolePermissionAssignmentRequestPermissionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Permissions, true
}

// SetPermissions sets field value
func (o *PostPermissionsRequest) SetPermissions(v []PostRolePermissionAssignmentRequestPermissionsInner) {
	o.Permissions = v
}

func (o PostPermissionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostPermissionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["permissions"] = o.Permissions
	return toSerialize, nil
}

func (o *PostPermissionsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"permissions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostPermissionsRequest := _PostPermissionsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostPermissionsRequest)

	if err != nil {
		return err
	}

	*o = PostPermissionsRequest(varPostPermissionsRequest)

	return err
}

type NullablePostPermissionsRequest struct {
	value *PostPermissionsRequest
	isSet bool
}

func (v NullablePostPermissionsRequest) Get() *PostPermissionsRequest {
	return v.value
}

func (v *NullablePostPermissionsRequest) Set(val *PostPermissionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostPermissionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostPermissionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostPermissionsRequest(val *PostPermissionsRequest) *NullablePostPermissionsRequest {
	return &NullablePostPermissionsRequest{value: val, isSet: true}
}

func (v NullablePostPermissionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostPermissionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
