// Code generated by Fern. DO NOT EDIT.

package management

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/auth0/go-auth0/v3/management/internal"
	big "math/big"
	time "time"
)

var (
	createEncryptionKeyPublicWrappingResponseContentFieldPublicKey = big.NewInt(1 << 0)
	createEncryptionKeyPublicWrappingResponseContentFieldAlgorithm = big.NewInt(1 << 1)
)

type CreateEncryptionKeyPublicWrappingResponseContent struct {
	// Public wrapping key in PEM format
	PublicKey string                               `json:"public_key" url:"public_key"`
	Algorithm EncryptionKeyPublicWrappingAlgorithm `json:"algorithm" url:"algorithm"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (c *CreateEncryptionKeyPublicWrappingResponseContent) GetPublicKey() string {
	if c == nil {
		return ""
	}
	return c.PublicKey
}

func (c *CreateEncryptionKeyPublicWrappingResponseContent) GetAlgorithm() EncryptionKeyPublicWrappingAlgorithm {
	if c == nil {
		return ""
	}
	return c.Algorithm
}

func (c *CreateEncryptionKeyPublicWrappingResponseContent) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.ExtraProperties
}

func (c *CreateEncryptionKeyPublicWrappingResponseContent) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetPublicKey sets the PublicKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateEncryptionKeyPublicWrappingResponseContent) SetPublicKey(publicKey string) {
	c.PublicKey = publicKey
	c.require(createEncryptionKeyPublicWrappingResponseContentFieldPublicKey)
}

// SetAlgorithm sets the Algorithm field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateEncryptionKeyPublicWrappingResponseContent) SetAlgorithm(algorithm EncryptionKeyPublicWrappingAlgorithm) {
	c.Algorithm = algorithm
	c.require(createEncryptionKeyPublicWrappingResponseContentFieldAlgorithm)
}

func (c *CreateEncryptionKeyPublicWrappingResponseContent) UnmarshalJSON(data []byte) error {
	type embed CreateEncryptionKeyPublicWrappingResponseContent
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreateEncryptionKeyPublicWrappingResponseContent(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.ExtraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateEncryptionKeyPublicWrappingResponseContent) MarshalJSON() ([]byte, error) {
	type embed CreateEncryptionKeyPublicWrappingResponseContent
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, c.ExtraProperties)
}

func (c *CreateEncryptionKeyPublicWrappingResponseContent) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Encryption key
var (
	createEncryptionKeyResponseContentFieldKid       = big.NewInt(1 << 0)
	createEncryptionKeyResponseContentFieldType      = big.NewInt(1 << 1)
	createEncryptionKeyResponseContentFieldState     = big.NewInt(1 << 2)
	createEncryptionKeyResponseContentFieldCreatedAt = big.NewInt(1 << 3)
	createEncryptionKeyResponseContentFieldUpdatedAt = big.NewInt(1 << 4)
	createEncryptionKeyResponseContentFieldParentKid = big.NewInt(1 << 5)
	createEncryptionKeyResponseContentFieldPublicKey = big.NewInt(1 << 6)
)

type CreateEncryptionKeyResponseContent struct {
	// Key ID
	Kid   string             `json:"kid" url:"kid"`
	Type  EncryptionKeyType  `json:"type" url:"type"`
	State EncryptionKeyState `json:"state" url:"state"`
	// Key creation timestamp
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// Key update timestamp
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`
	// ID of parent wrapping key
	ParentKid *string `json:"parent_kid,omitempty" url:"parent_kid,omitempty"`
	// Public key in PEM format
	PublicKey *string `json:"public_key,omitempty" url:"public_key,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateEncryptionKeyResponseContent) GetKid() string {
	if c == nil {
		return ""
	}
	return c.Kid
}

func (c *CreateEncryptionKeyResponseContent) GetType() EncryptionKeyType {
	if c == nil {
		return ""
	}
	return c.Type
}

func (c *CreateEncryptionKeyResponseContent) GetState() EncryptionKeyState {
	if c == nil {
		return ""
	}
	return c.State
}

func (c *CreateEncryptionKeyResponseContent) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CreateEncryptionKeyResponseContent) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *CreateEncryptionKeyResponseContent) GetParentKid() string {
	if c == nil || c.ParentKid == nil {
		return ""
	}
	return *c.ParentKid
}

func (c *CreateEncryptionKeyResponseContent) GetPublicKey() string {
	if c == nil || c.PublicKey == nil {
		return ""
	}
	return *c.PublicKey
}

func (c *CreateEncryptionKeyResponseContent) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateEncryptionKeyResponseContent) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetKid sets the Kid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateEncryptionKeyResponseContent) SetKid(kid string) {
	c.Kid = kid
	c.require(createEncryptionKeyResponseContentFieldKid)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateEncryptionKeyResponseContent) SetType(type_ EncryptionKeyType) {
	c.Type = type_
	c.require(createEncryptionKeyResponseContentFieldType)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateEncryptionKeyResponseContent) SetState(state EncryptionKeyState) {
	c.State = state
	c.require(createEncryptionKeyResponseContentFieldState)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateEncryptionKeyResponseContent) SetCreatedAt(createdAt time.Time) {
	c.CreatedAt = createdAt
	c.require(createEncryptionKeyResponseContentFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateEncryptionKeyResponseContent) SetUpdatedAt(updatedAt time.Time) {
	c.UpdatedAt = updatedAt
	c.require(createEncryptionKeyResponseContentFieldUpdatedAt)
}

// SetParentKid sets the ParentKid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateEncryptionKeyResponseContent) SetParentKid(parentKid *string) {
	c.ParentKid = parentKid
	c.require(createEncryptionKeyResponseContentFieldParentKid)
}

// SetPublicKey sets the PublicKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateEncryptionKeyResponseContent) SetPublicKey(publicKey *string) {
	c.PublicKey = publicKey
	c.require(createEncryptionKeyResponseContentFieldPublicKey)
}

func (c *CreateEncryptionKeyResponseContent) UnmarshalJSON(data []byte) error {
	type embed CreateEncryptionKeyResponseContent
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreateEncryptionKeyResponseContent(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateEncryptionKeyResponseContent) MarshalJSON() ([]byte, error) {
	type embed CreateEncryptionKeyResponseContent
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed:     embed(*c),
		CreatedAt: internal.NewDateTime(c.CreatedAt),
		UpdatedAt: internal.NewDateTime(c.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateEncryptionKeyResponseContent) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Type of the encryption key to be created.
type CreateEncryptionKeyType string

const (
	CreateEncryptionKeyTypeCustomerProvidedRootKey CreateEncryptionKeyType = "customer-provided-root-key"
	CreateEncryptionKeyTypeTenantEncryptionKey     CreateEncryptionKeyType = "tenant-encryption-key"
)

func NewCreateEncryptionKeyTypeFromString(s string) (CreateEncryptionKeyType, error) {
	switch s {
	case "customer-provided-root-key":
		return CreateEncryptionKeyTypeCustomerProvidedRootKey, nil
	case "tenant-encryption-key":
		return CreateEncryptionKeyTypeTenantEncryptionKey, nil
	}
	var t CreateEncryptionKeyType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateEncryptionKeyType) Ptr() *CreateEncryptionKeyType {
	return &c
}

var (
	createKeysNetworkACLsResponseContentFieldID          = big.NewInt(1 << 0)
	createKeysNetworkACLsResponseContentFieldName        = big.NewInt(1 << 1)
	createKeysNetworkACLsResponseContentFieldAlg         = big.NewInt(1 << 2)
	createKeysNetworkACLsResponseContentFieldFingerprint = big.NewInt(1 << 3)
	createKeysNetworkACLsResponseContentFieldCreatedAt   = big.NewInt(1 << 4)
	createKeysNetworkACLsResponseContentFieldUpdatedAt   = big.NewInt(1 << 5)
)

type CreateKeysNetworkACLsResponseContent struct {
	// Auth0-generated identifier for the key. Used to reference the key from a Network ACL and to identify it in Tenant Logs.
	ID string `json:"id" url:"id"`
	// Customer-supplied label with no cryptographic meaning.
	Name string                     `json:"name" url:"name"`
	Alg  NetworkACLKeyAlgorithmEnum `json:"alg" url:"alg"`
	// Fingerprint of the key material, determined by the algorithm specified. Currently only HMAC-SHA256 is supported.
	Fingerprint string `json:"fingerprint" url:"fingerprint"`
	// Time when the key was created.
	CreatedAt string `json:"created_at" url:"created_at"`
	// Time when the key was last updated.
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateKeysNetworkACLsResponseContent) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateKeysNetworkACLsResponseContent) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateKeysNetworkACLsResponseContent) GetAlg() NetworkACLKeyAlgorithmEnum {
	if c == nil {
		return ""
	}
	return c.Alg
}

func (c *CreateKeysNetworkACLsResponseContent) GetFingerprint() string {
	if c == nil {
		return ""
	}
	return c.Fingerprint
}

func (c *CreateKeysNetworkACLsResponseContent) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreateKeysNetworkACLsResponseContent) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *CreateKeysNetworkACLsResponseContent) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateKeysNetworkACLsResponseContent) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateKeysNetworkACLsResponseContent) SetID(id string) {
	c.ID = id
	c.require(createKeysNetworkACLsResponseContentFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateKeysNetworkACLsResponseContent) SetName(name string) {
	c.Name = name
	c.require(createKeysNetworkACLsResponseContentFieldName)
}

// SetAlg sets the Alg field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateKeysNetworkACLsResponseContent) SetAlg(alg NetworkACLKeyAlgorithmEnum) {
	c.Alg = alg
	c.require(createKeysNetworkACLsResponseContentFieldAlg)
}

// SetFingerprint sets the Fingerprint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateKeysNetworkACLsResponseContent) SetFingerprint(fingerprint string) {
	c.Fingerprint = fingerprint
	c.require(createKeysNetworkACLsResponseContentFieldFingerprint)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateKeysNetworkACLsResponseContent) SetCreatedAt(createdAt string) {
	c.CreatedAt = createdAt
	c.require(createKeysNetworkACLsResponseContentFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateKeysNetworkACLsResponseContent) SetUpdatedAt(updatedAt string) {
	c.UpdatedAt = updatedAt
	c.require(createKeysNetworkACLsResponseContentFieldUpdatedAt)
}

func (c *CreateKeysNetworkACLsResponseContent) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateKeysNetworkACLsResponseContent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateKeysNetworkACLsResponseContent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateKeysNetworkACLsResponseContent) MarshalJSON() ([]byte, error) {
	type embed CreateKeysNetworkACLsResponseContent
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateKeysNetworkACLsResponseContent) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Key algorithm
type CustomSigningKeyAlgorithmEnum string

const (
	CustomSigningKeyAlgorithmEnumRs256 CustomSigningKeyAlgorithmEnum = "RS256"
	CustomSigningKeyAlgorithmEnumRs384 CustomSigningKeyAlgorithmEnum = "RS384"
	CustomSigningKeyAlgorithmEnumRs512 CustomSigningKeyAlgorithmEnum = "RS512"
	CustomSigningKeyAlgorithmEnumEs256 CustomSigningKeyAlgorithmEnum = "ES256"
	CustomSigningKeyAlgorithmEnumEs384 CustomSigningKeyAlgorithmEnum = "ES384"
	CustomSigningKeyAlgorithmEnumEs512 CustomSigningKeyAlgorithmEnum = "ES512"
	CustomSigningKeyAlgorithmEnumPs256 CustomSigningKeyAlgorithmEnum = "PS256"
	CustomSigningKeyAlgorithmEnumPs384 CustomSigningKeyAlgorithmEnum = "PS384"
	CustomSigningKeyAlgorithmEnumPs512 CustomSigningKeyAlgorithmEnum = "PS512"
)

func NewCustomSigningKeyAlgorithmEnumFromString(s string) (CustomSigningKeyAlgorithmEnum, error) {
	switch s {
	case "RS256":
		return CustomSigningKeyAlgorithmEnumRs256, nil
	case "RS384":
		return CustomSigningKeyAlgorithmEnumRs384, nil
	case "RS512":
		return CustomSigningKeyAlgorithmEnumRs512, nil
	case "ES256":
		return CustomSigningKeyAlgorithmEnumEs256, nil
	case "ES384":
		return CustomSigningKeyAlgorithmEnumEs384, nil
	case "ES512":
		return CustomSigningKeyAlgorithmEnumEs512, nil
	case "PS256":
		return CustomSigningKeyAlgorithmEnumPs256, nil
	case "PS384":
		return CustomSigningKeyAlgorithmEnumPs384, nil
	case "PS512":
		return CustomSigningKeyAlgorithmEnumPs512, nil
	}
	var t CustomSigningKeyAlgorithmEnum
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomSigningKeyAlgorithmEnum) Ptr() *CustomSigningKeyAlgorithmEnum {
	return &c
}

// Curve
type CustomSigningKeyCurveEnum string

const (
	CustomSigningKeyCurveEnumP256 CustomSigningKeyCurveEnum = "P-256"
	CustomSigningKeyCurveEnumP384 CustomSigningKeyCurveEnum = "P-384"
	CustomSigningKeyCurveEnumP521 CustomSigningKeyCurveEnum = "P-521"
)

func NewCustomSigningKeyCurveEnumFromString(s string) (CustomSigningKeyCurveEnum, error) {
	switch s {
	case "P-256":
		return CustomSigningKeyCurveEnumP256, nil
	case "P-384":
		return CustomSigningKeyCurveEnumP384, nil
	case "P-521":
		return CustomSigningKeyCurveEnumP521, nil
	}
	var t CustomSigningKeyCurveEnum
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomSigningKeyCurveEnum) Ptr() *CustomSigningKeyCurveEnum {
	return &c
}

// JWK representing a custom public signing key.
var (
	customSigningKeyJwkFieldKty     = big.NewInt(1 << 0)
	customSigningKeyJwkFieldKid     = big.NewInt(1 << 1)
	customSigningKeyJwkFieldUse     = big.NewInt(1 << 2)
	customSigningKeyJwkFieldKeyOps  = big.NewInt(1 << 3)
	customSigningKeyJwkFieldAlg     = big.NewInt(1 << 4)
	customSigningKeyJwkFieldN       = big.NewInt(1 << 5)
	customSigningKeyJwkFieldE       = big.NewInt(1 << 6)
	customSigningKeyJwkFieldCrv     = big.NewInt(1 << 7)
	customSigningKeyJwkFieldX       = big.NewInt(1 << 8)
	customSigningKeyJwkFieldY       = big.NewInt(1 << 9)
	customSigningKeyJwkFieldX5U     = big.NewInt(1 << 10)
	customSigningKeyJwkFieldX5C     = big.NewInt(1 << 11)
	customSigningKeyJwkFieldX5T     = big.NewInt(1 << 12)
	customSigningKeyJwkFieldX5TS256 = big.NewInt(1 << 13)
)

type CustomSigningKeyJwk struct {
	Kty CustomSigningKeyTypeEnum `json:"kty" url:"kty"`
	// Key identifier
	Kid *string                  `json:"kid,omitempty" url:"kid,omitempty"`
	Use *CustomSigningKeyUseEnum `json:"use,omitempty" url:"use,omitempty"`
	// Key operations
	KeyOps []CustomSigningKeyOperationEnum `json:"key_ops,omitempty" url:"key_ops,omitempty"`
	Alg    *CustomSigningKeyAlgorithmEnum  `json:"alg,omitempty" url:"alg,omitempty"`
	// Key modulus
	N *string `json:"n,omitempty" url:"n,omitempty"`
	// Key exponent
	E   *string                    `json:"e,omitempty" url:"e,omitempty"`
	Crv *CustomSigningKeyCurveEnum `json:"crv,omitempty" url:"crv,omitempty"`
	// X coordinate
	X *string `json:"x,omitempty" url:"x,omitempty"`
	// Y coordinate
	Y *string `json:"y,omitempty" url:"y,omitempty"`
	// X.509 URL
	X5U *string `json:"x5u,omitempty" url:"x5u,omitempty"`
	// X.509 certificate chain
	X5C []string `json:"x5c,omitempty" url:"x5c,omitempty"`
	// X.509 certificate SHA-1 thumbprint
	X5T *string `json:"x5t,omitempty" url:"x5t,omitempty"`
	// X.509 certificate SHA-256 thumbprint
	X5TS256 *string `json:"x5t#S256,omitempty" url:"x5t#S256,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomSigningKeyJwk) GetKty() CustomSigningKeyTypeEnum {
	if c == nil {
		return ""
	}
	return c.Kty
}

func (c *CustomSigningKeyJwk) GetKid() string {
	if c == nil || c.Kid == nil {
		return ""
	}
	return *c.Kid
}

func (c *CustomSigningKeyJwk) GetUse() CustomSigningKeyUseEnum {
	if c == nil || c.Use == nil {
		return ""
	}
	return *c.Use
}

func (c *CustomSigningKeyJwk) GetKeyOps() []CustomSigningKeyOperationEnum {
	if c == nil || c.KeyOps == nil {
		return nil
	}
	return c.KeyOps
}

func (c *CustomSigningKeyJwk) GetAlg() CustomSigningKeyAlgorithmEnum {
	if c == nil || c.Alg == nil {
		return ""
	}
	return *c.Alg
}

func (c *CustomSigningKeyJwk) GetN() string {
	if c == nil || c.N == nil {
		return ""
	}
	return *c.N
}

func (c *CustomSigningKeyJwk) GetE() string {
	if c == nil || c.E == nil {
		return ""
	}
	return *c.E
}

func (c *CustomSigningKeyJwk) GetCrv() CustomSigningKeyCurveEnum {
	if c == nil || c.Crv == nil {
		return ""
	}
	return *c.Crv
}

func (c *CustomSigningKeyJwk) GetX() string {
	if c == nil || c.X == nil {
		return ""
	}
	return *c.X
}

func (c *CustomSigningKeyJwk) GetY() string {
	if c == nil || c.Y == nil {
		return ""
	}
	return *c.Y
}

func (c *CustomSigningKeyJwk) GetX5U() string {
	if c == nil || c.X5U == nil {
		return ""
	}
	return *c.X5U
}

func (c *CustomSigningKeyJwk) GetX5C() []string {
	if c == nil || c.X5C == nil {
		return nil
	}
	return c.X5C
}

func (c *CustomSigningKeyJwk) GetX5T() string {
	if c == nil || c.X5T == nil {
		return ""
	}
	return *c.X5T
}

func (c *CustomSigningKeyJwk) GetX5TS256() string {
	if c == nil || c.X5TS256 == nil {
		return ""
	}
	return *c.X5TS256
}

func (c *CustomSigningKeyJwk) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CustomSigningKeyJwk) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetKty sets the Kty field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSigningKeyJwk) SetKty(kty CustomSigningKeyTypeEnum) {
	c.Kty = kty
	c.require(customSigningKeyJwkFieldKty)
}

// SetKid sets the Kid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSigningKeyJwk) SetKid(kid *string) {
	c.Kid = kid
	c.require(customSigningKeyJwkFieldKid)
}

// SetUse sets the Use field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSigningKeyJwk) SetUse(use *CustomSigningKeyUseEnum) {
	c.Use = use
	c.require(customSigningKeyJwkFieldUse)
}

// SetKeyOps sets the KeyOps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSigningKeyJwk) SetKeyOps(keyOps []CustomSigningKeyOperationEnum) {
	c.KeyOps = keyOps
	c.require(customSigningKeyJwkFieldKeyOps)
}

// SetAlg sets the Alg field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSigningKeyJwk) SetAlg(alg *CustomSigningKeyAlgorithmEnum) {
	c.Alg = alg
	c.require(customSigningKeyJwkFieldAlg)
}

// SetN sets the N field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSigningKeyJwk) SetN(n *string) {
	c.N = n
	c.require(customSigningKeyJwkFieldN)
}

// SetE sets the E field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSigningKeyJwk) SetE(e *string) {
	c.E = e
	c.require(customSigningKeyJwkFieldE)
}

// SetCrv sets the Crv field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSigningKeyJwk) SetCrv(crv *CustomSigningKeyCurveEnum) {
	c.Crv = crv
	c.require(customSigningKeyJwkFieldCrv)
}

// SetX sets the X field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSigningKeyJwk) SetX(x *string) {
	c.X = x
	c.require(customSigningKeyJwkFieldX)
}

// SetY sets the Y field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSigningKeyJwk) SetY(y *string) {
	c.Y = y
	c.require(customSigningKeyJwkFieldY)
}

// SetX5U sets the X5U field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSigningKeyJwk) SetX5U(x5U *string) {
	c.X5U = x5U
	c.require(customSigningKeyJwkFieldX5U)
}

// SetX5C sets the X5C field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSigningKeyJwk) SetX5C(x5C []string) {
	c.X5C = x5C
	c.require(customSigningKeyJwkFieldX5C)
}

// SetX5T sets the X5T field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSigningKeyJwk) SetX5T(x5T *string) {
	c.X5T = x5T
	c.require(customSigningKeyJwkFieldX5T)
}

// SetX5TS256 sets the X5TS256 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSigningKeyJwk) SetX5TS256(x5TS256 *string) {
	c.X5TS256 = x5TS256
	c.require(customSigningKeyJwkFieldX5TS256)
}

func (c *CustomSigningKeyJwk) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomSigningKeyJwk
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomSigningKeyJwk(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomSigningKeyJwk) MarshalJSON() ([]byte, error) {
	type embed CustomSigningKeyJwk
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CustomSigningKeyJwk) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CustomSigningKeyOperationEnum string

const (
	CustomSigningKeyOperationEnumVerify CustomSigningKeyOperationEnum = "verify"
)

func NewCustomSigningKeyOperationEnumFromString(s string) (CustomSigningKeyOperationEnum, error) {
	switch s {
	case "verify":
		return CustomSigningKeyOperationEnumVerify, nil
	}
	var t CustomSigningKeyOperationEnum
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomSigningKeyOperationEnum) Ptr() *CustomSigningKeyOperationEnum {
	return &c
}

// Key type
type CustomSigningKeyTypeEnum string

const (
	CustomSigningKeyTypeEnumEc  CustomSigningKeyTypeEnum = "EC"
	CustomSigningKeyTypeEnumRsa CustomSigningKeyTypeEnum = "RSA"
)

func NewCustomSigningKeyTypeEnumFromString(s string) (CustomSigningKeyTypeEnum, error) {
	switch s {
	case "EC":
		return CustomSigningKeyTypeEnumEc, nil
	case "RSA":
		return CustomSigningKeyTypeEnumRsa, nil
	}
	var t CustomSigningKeyTypeEnum
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomSigningKeyTypeEnum) Ptr() *CustomSigningKeyTypeEnum {
	return &c
}

// Key use
type CustomSigningKeyUseEnum string

const (
	CustomSigningKeyUseEnumSig CustomSigningKeyUseEnum = "sig"
)

func NewCustomSigningKeyUseEnumFromString(s string) (CustomSigningKeyUseEnum, error) {
	switch s {
	case "sig":
		return CustomSigningKeyUseEnumSig, nil
	}
	var t CustomSigningKeyUseEnum
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomSigningKeyUseEnum) Ptr() *CustomSigningKeyUseEnum {
	return &c
}

// Encryption key
var (
	encryptionKeyFieldKid       = big.NewInt(1 << 0)
	encryptionKeyFieldType      = big.NewInt(1 << 1)
	encryptionKeyFieldState     = big.NewInt(1 << 2)
	encryptionKeyFieldCreatedAt = big.NewInt(1 << 3)
	encryptionKeyFieldUpdatedAt = big.NewInt(1 << 4)
	encryptionKeyFieldParentKid = big.NewInt(1 << 5)
	encryptionKeyFieldPublicKey = big.NewInt(1 << 6)
)

type EncryptionKey struct {
	// Key ID
	Kid   string             `json:"kid" url:"kid"`
	Type  EncryptionKeyType  `json:"type" url:"type"`
	State EncryptionKeyState `json:"state" url:"state"`
	// Key creation timestamp
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// Key update timestamp
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`
	// ID of parent wrapping key
	ParentKid *string `json:"parent_kid,omitempty" url:"parent_kid,omitempty"`
	// Public key in PEM format
	PublicKey *string `json:"public_key,omitempty" url:"public_key,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EncryptionKey) GetKid() string {
	if e == nil {
		return ""
	}
	return e.Kid
}

func (e *EncryptionKey) GetType() EncryptionKeyType {
	if e == nil {
		return ""
	}
	return e.Type
}

func (e *EncryptionKey) GetState() EncryptionKeyState {
	if e == nil {
		return ""
	}
	return e.State
}

func (e *EncryptionKey) GetCreatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.CreatedAt
}

func (e *EncryptionKey) GetUpdatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.UpdatedAt
}

func (e *EncryptionKey) GetParentKid() string {
	if e == nil || e.ParentKid == nil {
		return ""
	}
	return *e.ParentKid
}

func (e *EncryptionKey) GetPublicKey() string {
	if e == nil || e.PublicKey == nil {
		return ""
	}
	return *e.PublicKey
}

func (e *EncryptionKey) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EncryptionKey) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetKid sets the Kid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EncryptionKey) SetKid(kid string) {
	e.Kid = kid
	e.require(encryptionKeyFieldKid)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EncryptionKey) SetType(type_ EncryptionKeyType) {
	e.Type = type_
	e.require(encryptionKeyFieldType)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EncryptionKey) SetState(state EncryptionKeyState) {
	e.State = state
	e.require(encryptionKeyFieldState)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EncryptionKey) SetCreatedAt(createdAt time.Time) {
	e.CreatedAt = createdAt
	e.require(encryptionKeyFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EncryptionKey) SetUpdatedAt(updatedAt time.Time) {
	e.UpdatedAt = updatedAt
	e.require(encryptionKeyFieldUpdatedAt)
}

// SetParentKid sets the ParentKid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EncryptionKey) SetParentKid(parentKid *string) {
	e.ParentKid = parentKid
	e.require(encryptionKeyFieldParentKid)
}

// SetPublicKey sets the PublicKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EncryptionKey) SetPublicKey(publicKey *string) {
	e.PublicKey = publicKey
	e.require(encryptionKeyFieldPublicKey)
}

func (e *EncryptionKey) UnmarshalJSON(data []byte) error {
	type embed EncryptionKey
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*e),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*e = EncryptionKey(unmarshaler.embed)
	e.CreatedAt = unmarshaler.CreatedAt.Time()
	e.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EncryptionKey) MarshalJSON() ([]byte, error) {
	type embed EncryptionKey
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed:     embed(*e),
		CreatedAt: internal.NewDateTime(e.CreatedAt),
		UpdatedAt: internal.NewDateTime(e.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EncryptionKey) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// Encryption algorithm that shall be used to wrap your key material
type EncryptionKeyPublicWrappingAlgorithm string

const (
	EncryptionKeyPublicWrappingAlgorithmCkmRsaAesKeyWrap EncryptionKeyPublicWrappingAlgorithm = "CKM_RSA_AES_KEY_WRAP"
)

func NewEncryptionKeyPublicWrappingAlgorithmFromString(s string) (EncryptionKeyPublicWrappingAlgorithm, error) {
	switch s {
	case "CKM_RSA_AES_KEY_WRAP":
		return EncryptionKeyPublicWrappingAlgorithmCkmRsaAesKeyWrap, nil
	}
	var t EncryptionKeyPublicWrappingAlgorithm
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (e EncryptionKeyPublicWrappingAlgorithm) Ptr() *EncryptionKeyPublicWrappingAlgorithm {
	return &e
}

// Key state
type EncryptionKeyState string

const (
	EncryptionKeyStatePreActivation EncryptionKeyState = "pre-activation"
	EncryptionKeyStateActive        EncryptionKeyState = "active"
	EncryptionKeyStateDeactivated   EncryptionKeyState = "deactivated"
	EncryptionKeyStateDestroyed     EncryptionKeyState = "destroyed"
)

func NewEncryptionKeyStateFromString(s string) (EncryptionKeyState, error) {
	switch s {
	case "pre-activation":
		return EncryptionKeyStatePreActivation, nil
	case "active":
		return EncryptionKeyStateActive, nil
	case "deactivated":
		return EncryptionKeyStateDeactivated, nil
	case "destroyed":
		return EncryptionKeyStateDestroyed, nil
	}
	var t EncryptionKeyState
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (e EncryptionKeyState) Ptr() *EncryptionKeyState {
	return &e
}

// Key type
type EncryptionKeyType string

const (
	EncryptionKeyTypeCustomerProvidedRootKey EncryptionKeyType = "customer-provided-root-key"
	EncryptionKeyTypeEnvironmentRootKey      EncryptionKeyType = "environment-root-key"
	EncryptionKeyTypeTenantMasterKey         EncryptionKeyType = "tenant-master-key"
	EncryptionKeyTypeTenantEncryptionKey     EncryptionKeyType = "tenant-encryption-key"
)

func NewEncryptionKeyTypeFromString(s string) (EncryptionKeyType, error) {
	switch s {
	case "customer-provided-root-key":
		return EncryptionKeyTypeCustomerProvidedRootKey, nil
	case "environment-root-key":
		return EncryptionKeyTypeEnvironmentRootKey, nil
	case "tenant-master-key":
		return EncryptionKeyTypeTenantMasterKey, nil
	case "tenant-encryption-key":
		return EncryptionKeyTypeTenantEncryptionKey, nil
	}
	var t EncryptionKeyType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (e EncryptionKeyType) Ptr() *EncryptionKeyType {
	return &e
}

var (
	getAllKeysNetworkACLsResponseContentFieldKeys = big.NewInt(1 << 0)
)

type GetAllKeysNetworkACLsResponseContent struct {
	// The tenant's Network ACL Keys.
	Keys []*NetworkACLKey `json:"keys" url:"keys"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetAllKeysNetworkACLsResponseContent) GetKeys() []*NetworkACLKey {
	if g == nil {
		return nil
	}
	return g.Keys
}

func (g *GetAllKeysNetworkACLsResponseContent) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetAllKeysNetworkACLsResponseContent) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetKeys sets the Keys field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAllKeysNetworkACLsResponseContent) SetKeys(keys []*NetworkACLKey) {
	g.Keys = keys
	g.require(getAllKeysNetworkACLsResponseContentFieldKeys)
}

func (g *GetAllKeysNetworkACLsResponseContent) UnmarshalJSON(data []byte) error {
	type unmarshaler GetAllKeysNetworkACLsResponseContent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetAllKeysNetworkACLsResponseContent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetAllKeysNetworkACLsResponseContent) MarshalJSON() ([]byte, error) {
	type embed GetAllKeysNetworkACLsResponseContent
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetAllKeysNetworkACLsResponseContent) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// JWKS representing an array of custom public signing keys.
var (
	getCustomSigningKeysResponseContentFieldKeys = big.NewInt(1 << 0)
)

type GetCustomSigningKeysResponseContent struct {
	// An array of custom public signing keys.
	Keys []*CustomSigningKeyJwk `json:"keys,omitempty" url:"keys,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetCustomSigningKeysResponseContent) GetKeys() []*CustomSigningKeyJwk {
	if g == nil || g.Keys == nil {
		return nil
	}
	return g.Keys
}

func (g *GetCustomSigningKeysResponseContent) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetCustomSigningKeysResponseContent) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetKeys sets the Keys field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCustomSigningKeysResponseContent) SetKeys(keys []*CustomSigningKeyJwk) {
	g.Keys = keys
	g.require(getCustomSigningKeysResponseContentFieldKeys)
}

func (g *GetCustomSigningKeysResponseContent) UnmarshalJSON(data []byte) error {
	type unmarshaler GetCustomSigningKeysResponseContent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetCustomSigningKeysResponseContent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetCustomSigningKeysResponseContent) MarshalJSON() ([]byte, error) {
	type embed GetCustomSigningKeysResponseContent
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetCustomSigningKeysResponseContent) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Encryption key
var (
	getEncryptionKeyResponseContentFieldKid       = big.NewInt(1 << 0)
	getEncryptionKeyResponseContentFieldType      = big.NewInt(1 << 1)
	getEncryptionKeyResponseContentFieldState     = big.NewInt(1 << 2)
	getEncryptionKeyResponseContentFieldCreatedAt = big.NewInt(1 << 3)
	getEncryptionKeyResponseContentFieldUpdatedAt = big.NewInt(1 << 4)
	getEncryptionKeyResponseContentFieldParentKid = big.NewInt(1 << 5)
	getEncryptionKeyResponseContentFieldPublicKey = big.NewInt(1 << 6)
)

type GetEncryptionKeyResponseContent struct {
	// Key ID
	Kid   string             `json:"kid" url:"kid"`
	Type  EncryptionKeyType  `json:"type" url:"type"`
	State EncryptionKeyState `json:"state" url:"state"`
	// Key creation timestamp
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// Key update timestamp
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`
	// ID of parent wrapping key
	ParentKid *string `json:"parent_kid,omitempty" url:"parent_kid,omitempty"`
	// Public key in PEM format
	PublicKey *string `json:"public_key,omitempty" url:"public_key,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetEncryptionKeyResponseContent) GetKid() string {
	if g == nil {
		return ""
	}
	return g.Kid
}

func (g *GetEncryptionKeyResponseContent) GetType() EncryptionKeyType {
	if g == nil {
		return ""
	}
	return g.Type
}

func (g *GetEncryptionKeyResponseContent) GetState() EncryptionKeyState {
	if g == nil {
		return ""
	}
	return g.State
}

func (g *GetEncryptionKeyResponseContent) GetCreatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.CreatedAt
}

func (g *GetEncryptionKeyResponseContent) GetUpdatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.UpdatedAt
}

func (g *GetEncryptionKeyResponseContent) GetParentKid() string {
	if g == nil || g.ParentKid == nil {
		return ""
	}
	return *g.ParentKid
}

func (g *GetEncryptionKeyResponseContent) GetPublicKey() string {
	if g == nil || g.PublicKey == nil {
		return ""
	}
	return *g.PublicKey
}

func (g *GetEncryptionKeyResponseContent) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetEncryptionKeyResponseContent) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetKid sets the Kid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetEncryptionKeyResponseContent) SetKid(kid string) {
	g.Kid = kid
	g.require(getEncryptionKeyResponseContentFieldKid)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetEncryptionKeyResponseContent) SetType(type_ EncryptionKeyType) {
	g.Type = type_
	g.require(getEncryptionKeyResponseContentFieldType)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetEncryptionKeyResponseContent) SetState(state EncryptionKeyState) {
	g.State = state
	g.require(getEncryptionKeyResponseContentFieldState)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetEncryptionKeyResponseContent) SetCreatedAt(createdAt time.Time) {
	g.CreatedAt = createdAt
	g.require(getEncryptionKeyResponseContentFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetEncryptionKeyResponseContent) SetUpdatedAt(updatedAt time.Time) {
	g.UpdatedAt = updatedAt
	g.require(getEncryptionKeyResponseContentFieldUpdatedAt)
}

// SetParentKid sets the ParentKid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetEncryptionKeyResponseContent) SetParentKid(parentKid *string) {
	g.ParentKid = parentKid
	g.require(getEncryptionKeyResponseContentFieldParentKid)
}

// SetPublicKey sets the PublicKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetEncryptionKeyResponseContent) SetPublicKey(publicKey *string) {
	g.PublicKey = publicKey
	g.require(getEncryptionKeyResponseContentFieldPublicKey)
}

func (g *GetEncryptionKeyResponseContent) UnmarshalJSON(data []byte) error {
	type embed GetEncryptionKeyResponseContent
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GetEncryptionKeyResponseContent(unmarshaler.embed)
	g.CreatedAt = unmarshaler.CreatedAt.Time()
	g.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetEncryptionKeyResponseContent) MarshalJSON() ([]byte, error) {
	type embed GetEncryptionKeyResponseContent
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed:     embed(*g),
		CreatedAt: internal.NewDateTime(g.CreatedAt),
		UpdatedAt: internal.NewDateTime(g.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetEncryptionKeyResponseContent) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getSigningKeysResponseContentFieldKid          = big.NewInt(1 << 0)
	getSigningKeysResponseContentFieldCert         = big.NewInt(1 << 1)
	getSigningKeysResponseContentFieldPkcs7        = big.NewInt(1 << 2)
	getSigningKeysResponseContentFieldCurrent      = big.NewInt(1 << 3)
	getSigningKeysResponseContentFieldNext         = big.NewInt(1 << 4)
	getSigningKeysResponseContentFieldPrevious     = big.NewInt(1 << 5)
	getSigningKeysResponseContentFieldCurrentSince = big.NewInt(1 << 6)
	getSigningKeysResponseContentFieldCurrentUntil = big.NewInt(1 << 7)
	getSigningKeysResponseContentFieldFingerprint  = big.NewInt(1 << 8)
	getSigningKeysResponseContentFieldThumbprint   = big.NewInt(1 << 9)
	getSigningKeysResponseContentFieldRevoked      = big.NewInt(1 << 10)
	getSigningKeysResponseContentFieldRevokedAt    = big.NewInt(1 << 11)
)

type GetSigningKeysResponseContent struct {
	// The key id of the signing key
	Kid string `json:"kid" url:"kid"`
	// The public certificate of the signing key
	Cert string `json:"cert" url:"cert"`
	// The public certificate of the signing key in pkcs7 format
	Pkcs7 *string `json:"pkcs7,omitempty" url:"pkcs7,omitempty"`
	// True if the key is the the current key
	Current *bool `json:"current,omitempty" url:"current,omitempty"`
	// True if the key is the the next key
	Next *bool `json:"next,omitempty" url:"next,omitempty"`
	// True if the key is the the previous key
	Previous     *bool            `json:"previous,omitempty" url:"previous,omitempty"`
	CurrentSince *SigningKeysDate `json:"current_since,omitempty" url:"current_since,omitempty"`
	CurrentUntil *SigningKeysDate `json:"current_until,omitempty" url:"current_until,omitempty"`
	// The cert fingerprint
	Fingerprint string `json:"fingerprint" url:"fingerprint"`
	// The cert thumbprint
	Thumbprint string `json:"thumbprint" url:"thumbprint"`
	// True if the key is revoked
	Revoked   *bool            `json:"revoked,omitempty" url:"revoked,omitempty"`
	RevokedAt *SigningKeysDate `json:"revoked_at,omitempty" url:"revoked_at,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetSigningKeysResponseContent) GetKid() string {
	if g == nil {
		return ""
	}
	return g.Kid
}

func (g *GetSigningKeysResponseContent) GetCert() string {
	if g == nil {
		return ""
	}
	return g.Cert
}

func (g *GetSigningKeysResponseContent) GetPkcs7() string {
	if g == nil || g.Pkcs7 == nil {
		return ""
	}
	return *g.Pkcs7
}

func (g *GetSigningKeysResponseContent) GetCurrent() bool {
	if g == nil || g.Current == nil {
		return false
	}
	return *g.Current
}

func (g *GetSigningKeysResponseContent) GetNext() bool {
	if g == nil || g.Next == nil {
		return false
	}
	return *g.Next
}

func (g *GetSigningKeysResponseContent) GetPrevious() bool {
	if g == nil || g.Previous == nil {
		return false
	}
	return *g.Previous
}

func (g *GetSigningKeysResponseContent) GetCurrentSince() SigningKeysDate {
	if g == nil || g.CurrentSince == nil {
		return SigningKeysDate{}
	}
	return *g.CurrentSince
}

func (g *GetSigningKeysResponseContent) GetCurrentUntil() SigningKeysDate {
	if g == nil || g.CurrentUntil == nil {
		return SigningKeysDate{}
	}
	return *g.CurrentUntil
}

func (g *GetSigningKeysResponseContent) GetFingerprint() string {
	if g == nil {
		return ""
	}
	return g.Fingerprint
}

func (g *GetSigningKeysResponseContent) GetThumbprint() string {
	if g == nil {
		return ""
	}
	return g.Thumbprint
}

func (g *GetSigningKeysResponseContent) GetRevoked() bool {
	if g == nil || g.Revoked == nil {
		return false
	}
	return *g.Revoked
}

func (g *GetSigningKeysResponseContent) GetRevokedAt() SigningKeysDate {
	if g == nil || g.RevokedAt == nil {
		return SigningKeysDate{}
	}
	return *g.RevokedAt
}

func (g *GetSigningKeysResponseContent) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetSigningKeysResponseContent) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetKid sets the Kid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSigningKeysResponseContent) SetKid(kid string) {
	g.Kid = kid
	g.require(getSigningKeysResponseContentFieldKid)
}

// SetCert sets the Cert field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSigningKeysResponseContent) SetCert(cert string) {
	g.Cert = cert
	g.require(getSigningKeysResponseContentFieldCert)
}

// SetPkcs7 sets the Pkcs7 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSigningKeysResponseContent) SetPkcs7(pkcs7 *string) {
	g.Pkcs7 = pkcs7
	g.require(getSigningKeysResponseContentFieldPkcs7)
}

// SetCurrent sets the Current field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSigningKeysResponseContent) SetCurrent(current *bool) {
	g.Current = current
	g.require(getSigningKeysResponseContentFieldCurrent)
}

// SetNext sets the Next field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSigningKeysResponseContent) SetNext(next *bool) {
	g.Next = next
	g.require(getSigningKeysResponseContentFieldNext)
}

// SetPrevious sets the Previous field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSigningKeysResponseContent) SetPrevious(previous *bool) {
	g.Previous = previous
	g.require(getSigningKeysResponseContentFieldPrevious)
}

// SetCurrentSince sets the CurrentSince field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSigningKeysResponseContent) SetCurrentSince(currentSince *SigningKeysDate) {
	g.CurrentSince = currentSince
	g.require(getSigningKeysResponseContentFieldCurrentSince)
}

// SetCurrentUntil sets the CurrentUntil field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSigningKeysResponseContent) SetCurrentUntil(currentUntil *SigningKeysDate) {
	g.CurrentUntil = currentUntil
	g.require(getSigningKeysResponseContentFieldCurrentUntil)
}

// SetFingerprint sets the Fingerprint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSigningKeysResponseContent) SetFingerprint(fingerprint string) {
	g.Fingerprint = fingerprint
	g.require(getSigningKeysResponseContentFieldFingerprint)
}

// SetThumbprint sets the Thumbprint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSigningKeysResponseContent) SetThumbprint(thumbprint string) {
	g.Thumbprint = thumbprint
	g.require(getSigningKeysResponseContentFieldThumbprint)
}

// SetRevoked sets the Revoked field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSigningKeysResponseContent) SetRevoked(revoked *bool) {
	g.Revoked = revoked
	g.require(getSigningKeysResponseContentFieldRevoked)
}

// SetRevokedAt sets the RevokedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSigningKeysResponseContent) SetRevokedAt(revokedAt *SigningKeysDate) {
	g.RevokedAt = revokedAt
	g.require(getSigningKeysResponseContentFieldRevokedAt)
}

func (g *GetSigningKeysResponseContent) UnmarshalJSON(data []byte) error {
	type unmarshaler GetSigningKeysResponseContent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetSigningKeysResponseContent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetSigningKeysResponseContent) MarshalJSON() ([]byte, error) {
	type embed GetSigningKeysResponseContent
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetSigningKeysResponseContent) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Encryption key
var (
	importEncryptionKeyResponseContentFieldKid       = big.NewInt(1 << 0)
	importEncryptionKeyResponseContentFieldType      = big.NewInt(1 << 1)
	importEncryptionKeyResponseContentFieldState     = big.NewInt(1 << 2)
	importEncryptionKeyResponseContentFieldCreatedAt = big.NewInt(1 << 3)
	importEncryptionKeyResponseContentFieldUpdatedAt = big.NewInt(1 << 4)
	importEncryptionKeyResponseContentFieldParentKid = big.NewInt(1 << 5)
	importEncryptionKeyResponseContentFieldPublicKey = big.NewInt(1 << 6)
)

type ImportEncryptionKeyResponseContent struct {
	// Key ID
	Kid   string             `json:"kid" url:"kid"`
	Type  EncryptionKeyType  `json:"type" url:"type"`
	State EncryptionKeyState `json:"state" url:"state"`
	// Key creation timestamp
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// Key update timestamp
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`
	// ID of parent wrapping key
	ParentKid *string `json:"parent_kid,omitempty" url:"parent_kid,omitempty"`
	// Public key in PEM format
	PublicKey *string `json:"public_key,omitempty" url:"public_key,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *ImportEncryptionKeyResponseContent) GetKid() string {
	if i == nil {
		return ""
	}
	return i.Kid
}

func (i *ImportEncryptionKeyResponseContent) GetType() EncryptionKeyType {
	if i == nil {
		return ""
	}
	return i.Type
}

func (i *ImportEncryptionKeyResponseContent) GetState() EncryptionKeyState {
	if i == nil {
		return ""
	}
	return i.State
}

func (i *ImportEncryptionKeyResponseContent) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}

func (i *ImportEncryptionKeyResponseContent) GetUpdatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.UpdatedAt
}

func (i *ImportEncryptionKeyResponseContent) GetParentKid() string {
	if i == nil || i.ParentKid == nil {
		return ""
	}
	return *i.ParentKid
}

func (i *ImportEncryptionKeyResponseContent) GetPublicKey() string {
	if i == nil || i.PublicKey == nil {
		return ""
	}
	return *i.PublicKey
}

func (i *ImportEncryptionKeyResponseContent) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *ImportEncryptionKeyResponseContent) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetKid sets the Kid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportEncryptionKeyResponseContent) SetKid(kid string) {
	i.Kid = kid
	i.require(importEncryptionKeyResponseContentFieldKid)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportEncryptionKeyResponseContent) SetType(type_ EncryptionKeyType) {
	i.Type = type_
	i.require(importEncryptionKeyResponseContentFieldType)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportEncryptionKeyResponseContent) SetState(state EncryptionKeyState) {
	i.State = state
	i.require(importEncryptionKeyResponseContentFieldState)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportEncryptionKeyResponseContent) SetCreatedAt(createdAt time.Time) {
	i.CreatedAt = createdAt
	i.require(importEncryptionKeyResponseContentFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportEncryptionKeyResponseContent) SetUpdatedAt(updatedAt time.Time) {
	i.UpdatedAt = updatedAt
	i.require(importEncryptionKeyResponseContentFieldUpdatedAt)
}

// SetParentKid sets the ParentKid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportEncryptionKeyResponseContent) SetParentKid(parentKid *string) {
	i.ParentKid = parentKid
	i.require(importEncryptionKeyResponseContentFieldParentKid)
}

// SetPublicKey sets the PublicKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportEncryptionKeyResponseContent) SetPublicKey(publicKey *string) {
	i.PublicKey = publicKey
	i.require(importEncryptionKeyResponseContentFieldPublicKey)
}

func (i *ImportEncryptionKeyResponseContent) UnmarshalJSON(data []byte) error {
	type embed ImportEncryptionKeyResponseContent
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = ImportEncryptionKeyResponseContent(unmarshaler.embed)
	i.CreatedAt = unmarshaler.CreatedAt.Time()
	i.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *ImportEncryptionKeyResponseContent) MarshalJSON() ([]byte, error) {
	type embed ImportEncryptionKeyResponseContent
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed:     embed(*i),
		CreatedAt: internal.NewDateTime(i.CreatedAt),
		UpdatedAt: internal.NewDateTime(i.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *ImportEncryptionKeyResponseContent) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	listEncryptionKeyOffsetPaginatedResponseContentFieldStart = big.NewInt(1 << 0)
	listEncryptionKeyOffsetPaginatedResponseContentFieldLimit = big.NewInt(1 << 1)
	listEncryptionKeyOffsetPaginatedResponseContentFieldTotal = big.NewInt(1 << 2)
	listEncryptionKeyOffsetPaginatedResponseContentFieldKeys  = big.NewInt(1 << 3)
)

type ListEncryptionKeyOffsetPaginatedResponseContent struct {
	// Page index of the results to return. First page is 0.
	Start *int `json:"start,omitempty" url:"start,omitempty"`
	// Number of results per page.
	Limit *int `json:"limit,omitempty" url:"limit,omitempty"`
	// Total amount of encryption keys.
	Total *int `json:"total,omitempty" url:"total,omitempty"`
	// Encryption keys.
	Keys []*EncryptionKey `json:"keys,omitempty" url:"keys,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListEncryptionKeyOffsetPaginatedResponseContent) GetStart() int {
	if l == nil || l.Start == nil {
		return 0
	}
	return *l.Start
}

func (l *ListEncryptionKeyOffsetPaginatedResponseContent) GetLimit() int {
	if l == nil || l.Limit == nil {
		return 0
	}
	return *l.Limit
}

func (l *ListEncryptionKeyOffsetPaginatedResponseContent) GetTotal() int {
	if l == nil || l.Total == nil {
		return 0
	}
	return *l.Total
}

func (l *ListEncryptionKeyOffsetPaginatedResponseContent) GetKeys() []*EncryptionKey {
	if l == nil || l.Keys == nil {
		return nil
	}
	return l.Keys
}

func (l *ListEncryptionKeyOffsetPaginatedResponseContent) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListEncryptionKeyOffsetPaginatedResponseContent) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetStart sets the Start field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEncryptionKeyOffsetPaginatedResponseContent) SetStart(start *int) {
	l.Start = start
	l.require(listEncryptionKeyOffsetPaginatedResponseContentFieldStart)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEncryptionKeyOffsetPaginatedResponseContent) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listEncryptionKeyOffsetPaginatedResponseContentFieldLimit)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEncryptionKeyOffsetPaginatedResponseContent) SetTotal(total *int) {
	l.Total = total
	l.require(listEncryptionKeyOffsetPaginatedResponseContentFieldTotal)
}

// SetKeys sets the Keys field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEncryptionKeyOffsetPaginatedResponseContent) SetKeys(keys []*EncryptionKey) {
	l.Keys = keys
	l.require(listEncryptionKeyOffsetPaginatedResponseContentFieldKeys)
}

func (l *ListEncryptionKeyOffsetPaginatedResponseContent) UnmarshalJSON(data []byte) error {
	type unmarshaler ListEncryptionKeyOffsetPaginatedResponseContent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListEncryptionKeyOffsetPaginatedResponseContent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListEncryptionKeyOffsetPaginatedResponseContent) MarshalJSON() ([]byte, error) {
	type embed ListEncryptionKeyOffsetPaginatedResponseContent
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListEncryptionKeyOffsetPaginatedResponseContent) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type ListEncryptionKeysResponseContent struct {
	// Encryption keys.
	EncryptionKeyList                               []*EncryptionKey
	ListEncryptionKeyOffsetPaginatedResponseContent *ListEncryptionKeyOffsetPaginatedResponseContent

	typ string
}

func (l *ListEncryptionKeysResponseContent) GetEncryptionKeyList() []*EncryptionKey {
	if l == nil {
		return nil
	}
	return l.EncryptionKeyList
}

func (l *ListEncryptionKeysResponseContent) GetListEncryptionKeyOffsetPaginatedResponseContent() *ListEncryptionKeyOffsetPaginatedResponseContent {
	if l == nil {
		return nil
	}
	return l.ListEncryptionKeyOffsetPaginatedResponseContent
}

func (l *ListEncryptionKeysResponseContent) UnmarshalJSON(data []byte) error {
	var valueEncryptionKeyList []*EncryptionKey
	if err := json.Unmarshal(data, &valueEncryptionKeyList); err == nil {
		l.typ = "EncryptionKeyList"
		l.EncryptionKeyList = valueEncryptionKeyList
		return nil
	}
	valueListEncryptionKeyOffsetPaginatedResponseContent := new(ListEncryptionKeyOffsetPaginatedResponseContent)
	if err := json.Unmarshal(data, &valueListEncryptionKeyOffsetPaginatedResponseContent); err == nil {
		l.typ = "ListEncryptionKeyOffsetPaginatedResponseContent"
		l.ListEncryptionKeyOffsetPaginatedResponseContent = valueListEncryptionKeyOffsetPaginatedResponseContent
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, l)
}

func (l ListEncryptionKeysResponseContent) MarshalJSON() ([]byte, error) {
	if l.typ == "EncryptionKeyList" || l.EncryptionKeyList != nil {
		return json.Marshal(l.EncryptionKeyList)
	}
	if l.typ == "ListEncryptionKeyOffsetPaginatedResponseContent" || l.ListEncryptionKeyOffsetPaginatedResponseContent != nil {
		return json.Marshal(l.ListEncryptionKeyOffsetPaginatedResponseContent)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", l)
}

type ListEncryptionKeysResponseContentVisitor interface {
	VisitEncryptionKeyList([]*EncryptionKey) error
	VisitListEncryptionKeyOffsetPaginatedResponseContent(*ListEncryptionKeyOffsetPaginatedResponseContent) error
}

func (l *ListEncryptionKeysResponseContent) Accept(visitor ListEncryptionKeysResponseContentVisitor) error {
	if l.typ == "EncryptionKeyList" || l.EncryptionKeyList != nil {
		return visitor.VisitEncryptionKeyList(l.EncryptionKeyList)
	}
	if l.typ == "ListEncryptionKeyOffsetPaginatedResponseContent" || l.ListEncryptionKeyOffsetPaginatedResponseContent != nil {
		return visitor.VisitListEncryptionKeyOffsetPaginatedResponseContent(l.ListEncryptionKeyOffsetPaginatedResponseContent)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", l)
}

var (
	networkACLKeyFieldID          = big.NewInt(1 << 0)
	networkACLKeyFieldName        = big.NewInt(1 << 1)
	networkACLKeyFieldAlg         = big.NewInt(1 << 2)
	networkACLKeyFieldFingerprint = big.NewInt(1 << 3)
	networkACLKeyFieldCreatedAt   = big.NewInt(1 << 4)
	networkACLKeyFieldUpdatedAt   = big.NewInt(1 << 5)
)

type NetworkACLKey struct {
	// Generated identifier for the key. Used to reference the key from a Network ACL and to identify it in Tenant Logs.
	ID string `json:"id" url:"id"`
	// User supplied label for the key.
	Name string                     `json:"name" url:"name"`
	Alg  NetworkACLKeyAlgorithmEnum `json:"alg" url:"alg"`
	// Fingerprint of the key material, determined by the algorithm specified. Currently only HMAC-SHA256 is supported.
	Fingerprint string `json:"fingerprint" url:"fingerprint"`
	// Time when the key was created.
	CreatedAt string `json:"created_at" url:"created_at"`
	// Time when the key was last updated.
	UpdatedAt string `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NetworkACLKey) GetID() string {
	if n == nil {
		return ""
	}
	return n.ID
}

func (n *NetworkACLKey) GetName() string {
	if n == nil {
		return ""
	}
	return n.Name
}

func (n *NetworkACLKey) GetAlg() NetworkACLKeyAlgorithmEnum {
	if n == nil {
		return ""
	}
	return n.Alg
}

func (n *NetworkACLKey) GetFingerprint() string {
	if n == nil {
		return ""
	}
	return n.Fingerprint
}

func (n *NetworkACLKey) GetCreatedAt() string {
	if n == nil {
		return ""
	}
	return n.CreatedAt
}

func (n *NetworkACLKey) GetUpdatedAt() string {
	if n == nil {
		return ""
	}
	return n.UpdatedAt
}

func (n *NetworkACLKey) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NetworkACLKey) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLKey) SetID(id string) {
	n.ID = id
	n.require(networkACLKeyFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLKey) SetName(name string) {
	n.Name = name
	n.require(networkACLKeyFieldName)
}

// SetAlg sets the Alg field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLKey) SetAlg(alg NetworkACLKeyAlgorithmEnum) {
	n.Alg = alg
	n.require(networkACLKeyFieldAlg)
}

// SetFingerprint sets the Fingerprint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLKey) SetFingerprint(fingerprint string) {
	n.Fingerprint = fingerprint
	n.require(networkACLKeyFieldFingerprint)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLKey) SetCreatedAt(createdAt string) {
	n.CreatedAt = createdAt
	n.require(networkACLKeyFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkACLKey) SetUpdatedAt(updatedAt string) {
	n.UpdatedAt = updatedAt
	n.require(networkACLKeyFieldUpdatedAt)
}

func (n *NetworkACLKey) UnmarshalJSON(data []byte) error {
	type unmarshaler NetworkACLKey
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NetworkACLKey(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NetworkACLKey) MarshalJSON() ([]byte, error) {
	type embed NetworkACLKey
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NetworkACLKey) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

// Signing algorithm used to verify the signature. Currently only HMAC-SHA256 is supported.
type NetworkACLKeyAlgorithmEnum string

const (
	NetworkACLKeyAlgorithmEnumHmacSha256 NetworkACLKeyAlgorithmEnum = "hmac-sha256"
)

func NewNetworkACLKeyAlgorithmEnumFromString(s string) (NetworkACLKeyAlgorithmEnum, error) {
	switch s {
	case "hmac-sha256":
		return NetworkACLKeyAlgorithmEnumHmacSha256, nil
	}
	var t NetworkACLKeyAlgorithmEnum
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (n NetworkACLKeyAlgorithmEnum) Ptr() *NetworkACLKeyAlgorithmEnum {
	return &n
}

var (
	revokedSigningKeysResponseContentFieldCert = big.NewInt(1 << 0)
	revokedSigningKeysResponseContentFieldKid  = big.NewInt(1 << 1)
)

type RevokedSigningKeysResponseContent struct {
	// Revoked key certificate
	Cert string `json:"cert" url:"cert"`
	// Revoked key id
	Kid string `json:"kid" url:"kid"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (r *RevokedSigningKeysResponseContent) GetCert() string {
	if r == nil {
		return ""
	}
	return r.Cert
}

func (r *RevokedSigningKeysResponseContent) GetKid() string {
	if r == nil {
		return ""
	}
	return r.Kid
}

func (r *RevokedSigningKeysResponseContent) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.ExtraProperties
}

func (r *RevokedSigningKeysResponseContent) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetCert sets the Cert field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokedSigningKeysResponseContent) SetCert(cert string) {
	r.Cert = cert
	r.require(revokedSigningKeysResponseContentFieldCert)
}

// SetKid sets the Kid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokedSigningKeysResponseContent) SetKid(kid string) {
	r.Kid = kid
	r.require(revokedSigningKeysResponseContentFieldKid)
}

func (r *RevokedSigningKeysResponseContent) UnmarshalJSON(data []byte) error {
	type embed RevokedSigningKeysResponseContent
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RevokedSigningKeysResponseContent(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.ExtraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RevokedSigningKeysResponseContent) MarshalJSON() ([]byte, error) {
	type embed RevokedSigningKeysResponseContent
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, r.ExtraProperties)
}

func (r *RevokedSigningKeysResponseContent) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	rotateSigningKeysResponseContentFieldCert = big.NewInt(1 << 0)
	rotateSigningKeysResponseContentFieldKid  = big.NewInt(1 << 1)
)

type RotateSigningKeysResponseContent struct {
	// Next key certificate
	Cert string `json:"cert" url:"cert"`
	// Next key id
	Kid string `json:"kid" url:"kid"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (r *RotateSigningKeysResponseContent) GetCert() string {
	if r == nil {
		return ""
	}
	return r.Cert
}

func (r *RotateSigningKeysResponseContent) GetKid() string {
	if r == nil {
		return ""
	}
	return r.Kid
}

func (r *RotateSigningKeysResponseContent) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.ExtraProperties
}

func (r *RotateSigningKeysResponseContent) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetCert sets the Cert field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RotateSigningKeysResponseContent) SetCert(cert string) {
	r.Cert = cert
	r.require(rotateSigningKeysResponseContentFieldCert)
}

// SetKid sets the Kid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RotateSigningKeysResponseContent) SetKid(kid string) {
	r.Kid = kid
	r.require(rotateSigningKeysResponseContentFieldKid)
}

func (r *RotateSigningKeysResponseContent) UnmarshalJSON(data []byte) error {
	type embed RotateSigningKeysResponseContent
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RotateSigningKeysResponseContent(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.ExtraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RotateSigningKeysResponseContent) MarshalJSON() ([]byte, error) {
	type embed RotateSigningKeysResponseContent
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, r.ExtraProperties)
}

func (r *RotateSigningKeysResponseContent) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// JWKS representing an array of custom public signing keys.
var (
	setCustomSigningKeysResponseContentFieldKeys = big.NewInt(1 << 0)
)

type SetCustomSigningKeysResponseContent struct {
	// An array of custom public signing keys.
	Keys []*CustomSigningKeyJwk `json:"keys,omitempty" url:"keys,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SetCustomSigningKeysResponseContent) GetKeys() []*CustomSigningKeyJwk {
	if s == nil || s.Keys == nil {
		return nil
	}
	return s.Keys
}

func (s *SetCustomSigningKeysResponseContent) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SetCustomSigningKeysResponseContent) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetKeys sets the Keys field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetCustomSigningKeysResponseContent) SetKeys(keys []*CustomSigningKeyJwk) {
	s.Keys = keys
	s.require(setCustomSigningKeysResponseContentFieldKeys)
}

func (s *SetCustomSigningKeysResponseContent) UnmarshalJSON(data []byte) error {
	type unmarshaler SetCustomSigningKeysResponseContent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SetCustomSigningKeysResponseContent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SetCustomSigningKeysResponseContent) MarshalJSON() ([]byte, error) {
	type embed SetCustomSigningKeysResponseContent
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SetCustomSigningKeysResponseContent) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	signingKeysFieldKid          = big.NewInt(1 << 0)
	signingKeysFieldCert         = big.NewInt(1 << 1)
	signingKeysFieldPkcs7        = big.NewInt(1 << 2)
	signingKeysFieldCurrent      = big.NewInt(1 << 3)
	signingKeysFieldNext         = big.NewInt(1 << 4)
	signingKeysFieldPrevious     = big.NewInt(1 << 5)
	signingKeysFieldCurrentSince = big.NewInt(1 << 6)
	signingKeysFieldCurrentUntil = big.NewInt(1 << 7)
	signingKeysFieldFingerprint  = big.NewInt(1 << 8)
	signingKeysFieldThumbprint   = big.NewInt(1 << 9)
	signingKeysFieldRevoked      = big.NewInt(1 << 10)
	signingKeysFieldRevokedAt    = big.NewInt(1 << 11)
)

type SigningKeys struct {
	// The key id of the signing key
	Kid string `json:"kid" url:"kid"`
	// The public certificate of the signing key
	Cert string `json:"cert" url:"cert"`
	// The public certificate of the signing key in pkcs7 format
	Pkcs7 *string `json:"pkcs7,omitempty" url:"pkcs7,omitempty"`
	// True if the key is the the current key
	Current *bool `json:"current,omitempty" url:"current,omitempty"`
	// True if the key is the the next key
	Next *bool `json:"next,omitempty" url:"next,omitempty"`
	// True if the key is the the previous key
	Previous     *bool            `json:"previous,omitempty" url:"previous,omitempty"`
	CurrentSince *SigningKeysDate `json:"current_since,omitempty" url:"current_since,omitempty"`
	CurrentUntil *SigningKeysDate `json:"current_until,omitempty" url:"current_until,omitempty"`
	// The cert fingerprint
	Fingerprint string `json:"fingerprint" url:"fingerprint"`
	// The cert thumbprint
	Thumbprint string `json:"thumbprint" url:"thumbprint"`
	// True if the key is revoked
	Revoked   *bool            `json:"revoked,omitempty" url:"revoked,omitempty"`
	RevokedAt *SigningKeysDate `json:"revoked_at,omitempty" url:"revoked_at,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SigningKeys) GetKid() string {
	if s == nil {
		return ""
	}
	return s.Kid
}

func (s *SigningKeys) GetCert() string {
	if s == nil {
		return ""
	}
	return s.Cert
}

func (s *SigningKeys) GetPkcs7() string {
	if s == nil || s.Pkcs7 == nil {
		return ""
	}
	return *s.Pkcs7
}

func (s *SigningKeys) GetCurrent() bool {
	if s == nil || s.Current == nil {
		return false
	}
	return *s.Current
}

func (s *SigningKeys) GetNext() bool {
	if s == nil || s.Next == nil {
		return false
	}
	return *s.Next
}

func (s *SigningKeys) GetPrevious() bool {
	if s == nil || s.Previous == nil {
		return false
	}
	return *s.Previous
}

func (s *SigningKeys) GetCurrentSince() SigningKeysDate {
	if s == nil || s.CurrentSince == nil {
		return SigningKeysDate{}
	}
	return *s.CurrentSince
}

func (s *SigningKeys) GetCurrentUntil() SigningKeysDate {
	if s == nil || s.CurrentUntil == nil {
		return SigningKeysDate{}
	}
	return *s.CurrentUntil
}

func (s *SigningKeys) GetFingerprint() string {
	if s == nil {
		return ""
	}
	return s.Fingerprint
}

func (s *SigningKeys) GetThumbprint() string {
	if s == nil {
		return ""
	}
	return s.Thumbprint
}

func (s *SigningKeys) GetRevoked() bool {
	if s == nil || s.Revoked == nil {
		return false
	}
	return *s.Revoked
}

func (s *SigningKeys) GetRevokedAt() SigningKeysDate {
	if s == nil || s.RevokedAt == nil {
		return SigningKeysDate{}
	}
	return *s.RevokedAt
}

func (s *SigningKeys) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SigningKeys) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetKid sets the Kid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SigningKeys) SetKid(kid string) {
	s.Kid = kid
	s.require(signingKeysFieldKid)
}

// SetCert sets the Cert field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SigningKeys) SetCert(cert string) {
	s.Cert = cert
	s.require(signingKeysFieldCert)
}

// SetPkcs7 sets the Pkcs7 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SigningKeys) SetPkcs7(pkcs7 *string) {
	s.Pkcs7 = pkcs7
	s.require(signingKeysFieldPkcs7)
}

// SetCurrent sets the Current field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SigningKeys) SetCurrent(current *bool) {
	s.Current = current
	s.require(signingKeysFieldCurrent)
}

// SetNext sets the Next field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SigningKeys) SetNext(next *bool) {
	s.Next = next
	s.require(signingKeysFieldNext)
}

// SetPrevious sets the Previous field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SigningKeys) SetPrevious(previous *bool) {
	s.Previous = previous
	s.require(signingKeysFieldPrevious)
}

// SetCurrentSince sets the CurrentSince field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SigningKeys) SetCurrentSince(currentSince *SigningKeysDate) {
	s.CurrentSince = currentSince
	s.require(signingKeysFieldCurrentSince)
}

// SetCurrentUntil sets the CurrentUntil field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SigningKeys) SetCurrentUntil(currentUntil *SigningKeysDate) {
	s.CurrentUntil = currentUntil
	s.require(signingKeysFieldCurrentUntil)
}

// SetFingerprint sets the Fingerprint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SigningKeys) SetFingerprint(fingerprint string) {
	s.Fingerprint = fingerprint
	s.require(signingKeysFieldFingerprint)
}

// SetThumbprint sets the Thumbprint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SigningKeys) SetThumbprint(thumbprint string) {
	s.Thumbprint = thumbprint
	s.require(signingKeysFieldThumbprint)
}

// SetRevoked sets the Revoked field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SigningKeys) SetRevoked(revoked *bool) {
	s.Revoked = revoked
	s.require(signingKeysFieldRevoked)
}

// SetRevokedAt sets the RevokedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SigningKeys) SetRevokedAt(revokedAt *SigningKeysDate) {
	s.RevokedAt = revokedAt
	s.require(signingKeysFieldRevokedAt)
}

func (s *SigningKeys) UnmarshalJSON(data []byte) error {
	type unmarshaler SigningKeys
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SigningKeys(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SigningKeys) MarshalJSON() ([]byte, error) {
	type embed SigningKeys
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SigningKeys) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SigningKeysDate struct {
	// The date and time when the key became the current key
	String string
	// The date and time when the key became the current key
	StringUnknownMap map[string]any

	typ string
}

func (s *SigningKeysDate) GetString() string {
	if s == nil {
		return ""
	}
	return s.String
}

func (s *SigningKeysDate) GetStringUnknownMap() map[string]any {
	if s == nil {
		return nil
	}
	return s.StringUnknownMap
}

func (s *SigningKeysDate) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		s.typ = "String"
		s.String = valueString
		return nil
	}
	var valueStringUnknownMap map[string]any
	if err := json.Unmarshal(data, &valueStringUnknownMap); err == nil {
		s.typ = "StringUnknownMap"
		s.StringUnknownMap = valueStringUnknownMap
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, s)
}

func (s SigningKeysDate) MarshalJSON() ([]byte, error) {
	if s.typ == "String" || s.String != "" {
		return json.Marshal(s.String)
	}
	if s.typ == "StringUnknownMap" || s.StringUnknownMap != nil {
		return json.Marshal(s.StringUnknownMap)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", s)
}

type SigningKeysDateVisitor interface {
	VisitString(string) error
	VisitStringUnknownMap(map[string]any) error
}

func (s *SigningKeysDate) Accept(visitor SigningKeysDateVisitor) error {
	if s.typ == "String" || s.String != "" {
		return visitor.VisitString(s.String)
	}
	if s.typ == "StringUnknownMap" || s.StringUnknownMap != nil {
		return visitor.VisitStringUnknownMap(s.StringUnknownMap)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", s)
}
