// Code generated by Fern. DO NOT EDIT.

package variations

import (
	context "context"

	management "github.com/auth0/go-auth0/v2/management"
	core "github.com/auth0/go-auth0/v2/management/core"
	internal "github.com/auth0/go-auth0/v2/management/internal"
	option "github.com/auth0/go-auth0/v2/management/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Retrieve all variations defined for a specific feature flag.
func (c *Client) List(
	ctx context.Context,
	// The ID of the parent feature flag.
	id string,
	opts ...option.RequestOption,
) (*management.ListVariationsResponseContent, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new variation with parameter overrides for a specific feature flag.
func (c *Client) Create(
	ctx context.Context,
	// The ID of the parent feature flag.
	id string,
	request *management.CreateVariationRequestContent,
	opts ...option.RequestOption,
) (*management.CreateVariationResponseContent, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a single variation by its ID.
func (c *Client) Get(
	ctx context.Context,
	// The ID of the parent feature flag.
	id string,
	// The ID of the variation to retrieve.
	vid string,
	opts ...option.RequestOption,
) (*management.GetVariationResponseContent, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		id,
		vid,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a variation by ID. Returns 204 if the variation does not exist. Returns 404 if the parent feature flag does not exist.
func (c *Client) Delete(
	ctx context.Context,
	// The ID of the parent feature flag.
	id string,
	// The ID of the variation to delete.
	vid string,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		id,
		vid,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Partially update a variation by ID. Only provided fields are updated.
func (c *Client) Update(
	ctx context.Context,
	// The ID of the parent feature flag.
	id string,
	// The ID of the variation to update.
	vid string,
	request *management.UpdateVariationRequestContent,
	opts ...option.RequestOption,
) (*management.UpdateVariationResponseContent, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		id,
		vid,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
