// Code generated by Fern. DO NOT EDIT.

package branding_phone_templates_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	management "github.com/auth0/go-auth0/v2/management"
	client "github.com/auth0/go-auth0/v2/management/client"
	option "github.com/auth0/go-auth0/v2/management/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestBrandingPhoneTemplatesListWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &management.ListPhoneTemplatesRequestParameters{
		Disabled: management.Bool(
			true,
		),
	}
	_, invocationErr := client.Branding.Phone.Templates.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBrandingPhoneTemplatesListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBrandingPhoneTemplatesListWithWireMock", "GET", "/branding/phone/templates", map[string]string{"disabled": "true"}, 1)
}

func TestBrandingPhoneTemplatesCreateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &management.CreatePhoneTemplateRequestContent{}
	_, invocationErr := client.Branding.Phone.Templates.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBrandingPhoneTemplatesCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBrandingPhoneTemplatesCreateWithWireMock", "POST", "/branding/phone/templates", nil, 1)
}

func TestBrandingPhoneTemplatesGetWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Branding.Phone.Templates.Get(
		context.TODO(),
		"id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBrandingPhoneTemplatesGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBrandingPhoneTemplatesGetWithWireMock", "GET", "/branding/phone/templates/id", nil, 1)
}

func TestBrandingPhoneTemplatesDeleteWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	invocationErr := client.Branding.Phone.Templates.Delete(
		context.TODO(),
		"id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBrandingPhoneTemplatesDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBrandingPhoneTemplatesDeleteWithWireMock", "DELETE", "/branding/phone/templates/id", nil, 1)
}

func TestBrandingPhoneTemplatesUpdateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &management.UpdatePhoneTemplateRequestContent{}
	_, invocationErr := client.Branding.Phone.Templates.Update(
		context.TODO(),
		"id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBrandingPhoneTemplatesUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBrandingPhoneTemplatesUpdateWithWireMock", "PATCH", "/branding/phone/templates/id", nil, 1)
}

func TestBrandingPhoneTemplatesResetWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := map[string]any{
		"key": "value",
	}
	_, invocationErr := client.Branding.Phone.Templates.Reset(
		context.TODO(),
		"id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBrandingPhoneTemplatesResetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBrandingPhoneTemplatesResetWithWireMock", "PATCH", "/branding/phone/templates/id/reset", nil, 1)
}

func TestBrandingPhoneTemplatesTestWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &management.CreatePhoneTemplateTestNotificationRequestContent{
		To: "to",
	}
	_, invocationErr := client.Branding.Phone.Templates.Test(
		context.TODO(),
		"id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBrandingPhoneTemplatesTestWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBrandingPhoneTemplatesTestWithWireMock", "POST", "/branding/phone/templates/id/try", nil, 1)
}
