// Code generated by Fern. DO NOT EDIT.

package attackprotection

import (
	context "context"

	management "github.com/auth0/go-auth0/v3/management"
	core "github.com/auth0/go-auth0/v3/management/core"
	internal "github.com/auth0/go-auth0/v3/management/internal"
	option "github.com/auth0/go-auth0/v3/management/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Get the Bot Detection configuration of your tenant.
func (c *Client) GetBotDetection(
	ctx context.Context,
	opts ...option.RequestOption,
) (*management.GetBotDetectionSettingsResponseContent, error) {
	response, err := c.WithRawResponse.GetBotDetection(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update the Bot Detection configuration of your tenant.
func (c *Client) PatchBotDetection(
	ctx context.Context,
	request *management.UpdateBotDetectionSettingsRequestContent,
	opts ...option.RequestOption,
) (*management.UpdateBotDetectionSettingsResponseContent, error) {
	response, err := c.WithRawResponse.PatchBotDetection(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve details of the Breached Password Detection configuration of your tenant.
func (c *Client) GetBreachedPasswordDetection(
	ctx context.Context,
	opts ...option.RequestOption,
) (*management.GetBreachedPasswordDetectionSettingsResponseContent, error) {
	response, err := c.WithRawResponse.GetBreachedPasswordDetection(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update details of the Breached Password Detection configuration of your tenant.
func (c *Client) PatchBreachedPasswordDetection(
	ctx context.Context,
	request *management.UpdateBreachedPasswordDetectionSettingsRequestContent,
	opts ...option.RequestOption,
) (*management.UpdateBreachedPasswordDetectionSettingsResponseContent, error) {
	response, err := c.WithRawResponse.PatchBreachedPasswordDetection(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve details of the Brute-force Protection configuration of your tenant.
func (c *Client) GetBruteForceProtection(
	ctx context.Context,
	opts ...option.RequestOption,
) (*management.GetBruteForceSettingsResponseContent, error) {
	response, err := c.WithRawResponse.GetBruteForceProtection(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update the Brute-force Protection configuration of your tenant.
func (c *Client) PatchBruteForceProtection(
	ctx context.Context,
	request *management.UpdateBruteForceSettingsRequestContent,
	opts ...option.RequestOption,
) (*management.UpdateBruteForceSettingsResponseContent, error) {
	response, err := c.WithRawResponse.PatchBruteForceProtection(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get the CAPTCHA configuration for your client.
func (c *Client) GetCaptcha(
	ctx context.Context,
	opts ...option.RequestOption,
) (*management.GetAttackProtectionCaptchaResponseContent, error) {
	response, err := c.WithRawResponse.GetCaptcha(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update existing CAPTCHA configuration for your client.
func (c *Client) PatchCaptcha(
	ctx context.Context,
	request *management.UpdateAttackProtectionCaptchaRequestContent,
	opts ...option.RequestOption,
) (*management.UpdateAttackProtectionCaptchaResponseContent, error) {
	response, err := c.WithRawResponse.PatchCaptcha(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get the phone provider protection configuration for a tenant.
func (c *Client) GetPhoneProviderProtection(
	ctx context.Context,
	opts ...option.RequestOption,
) (*management.GetPhoneProviderProtectionResponseContent, error) {
	response, err := c.WithRawResponse.GetPhoneProviderProtection(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update the phone provider protection configuration for a tenant.
func (c *Client) PatchPhoneProviderProtection(
	ctx context.Context,
	request *management.PatchPhoneProviderProtectionRequestContent,
	opts ...option.RequestOption,
) (*management.PatchPhoneProviderProtectionResponseContent, error) {
	response, err := c.WithRawResponse.PatchPhoneProviderProtection(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve details of the Suspicious IP Throttling configuration of your tenant.
func (c *Client) GetSuspiciousIPThrottling(
	ctx context.Context,
	opts ...option.RequestOption,
) (*management.GetSuspiciousIPThrottlingSettingsResponseContent, error) {
	response, err := c.WithRawResponse.GetSuspiciousIPThrottling(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update the details of the Suspicious IP Throttling configuration of your tenant.
func (c *Client) PatchSuspiciousIPThrottling(
	ctx context.Context,
	request *management.UpdateSuspiciousIPThrottlingSettingsRequestContent,
	opts ...option.RequestOption,
) (*management.UpdateSuspiciousIPThrottlingSettingsResponseContent, error) {
	response, err := c.WithRawResponse.PatchSuspiciousIPThrottling(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
