// Code generated by Fern. DO NOT EDIT.

package experimentation_feature_flags_variations_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	management "github.com/auth0/go-auth0/v2/management"
	client "github.com/auth0/go-auth0/v2/management/client"
	option "github.com/auth0/go-auth0/v2/management/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestExperimentationFeatureFlagsVariationsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	_, invocationErr := client.Experimentation.FeatureFlags.Variations.List(
		context.TODO(),
		"id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestExperimentationFeatureFlagsVariationsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestExperimentationFeatureFlagsVariationsListWithWireMock", "GET", "/experimentation/feature-flags/id/variations", nil, 1)
}

func TestExperimentationFeatureFlagsVariationsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &management.CreateVariationRequestContent{
		Name:      "name",
		Overrides: map[string]*management.VariationOverrideValue{},
	}
	_, invocationErr := client.Experimentation.FeatureFlags.Variations.Create(
		context.TODO(),
		"id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestExperimentationFeatureFlagsVariationsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestExperimentationFeatureFlagsVariationsCreateWithWireMock", "POST", "/experimentation/feature-flags/id/variations", nil, 1)
}

func TestExperimentationFeatureFlagsVariationsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	_, invocationErr := client.Experimentation.FeatureFlags.Variations.Get(
		context.TODO(),
		"id",
		"vid",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestExperimentationFeatureFlagsVariationsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestExperimentationFeatureFlagsVariationsGetWithWireMock", "GET", "/experimentation/feature-flags/id/variations/vid", nil, 1)
}

func TestExperimentationFeatureFlagsVariationsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	invocationErr := client.Experimentation.FeatureFlags.Variations.Delete(
		context.TODO(),
		"id",
		"vid",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestExperimentationFeatureFlagsVariationsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestExperimentationFeatureFlagsVariationsDeleteWithWireMock", "DELETE", "/experimentation/feature-flags/id/variations/vid", nil, 1)
}

func TestExperimentationFeatureFlagsVariationsUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWithOptions(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &management.UpdateVariationRequestContent{}
	_, invocationErr := client.Experimentation.FeatureFlags.Variations.Update(
		context.TODO(),
		"id",
		"vid",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestExperimentationFeatureFlagsVariationsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestExperimentationFeatureFlagsVariationsUpdateWithWireMock", "PATCH", "/experimentation/feature-flags/id/variations/vid", nil, 1)
}
