// Code generated by Fern. DO NOT EDIT.

package guardian

import (
	management "github.com/auth0/go-auth0/v2/management"
)

type CreateGuardianEnrollmentTicketRequestContent struct {
	// user_id for the enrollment ticket
	UserID string `json:"user_id" url:"-"`
	// alternate email to which the enrollment email will be sent. Optional - by default, the email will be sent to the user's default address
	Email *string `json:"email,omitempty" url:"-"`
	// Send an email to the user to start the enrollment
	SendMail *bool `json:"send_mail,omitempty" url:"-"`
	// Optional. Specify the locale of the enrollment email. Used with send_email.
	EmailLocale *string                                  `json:"email_locale,omitempty" url:"-"`
	Factor      *management.GuardianEnrollmentFactorEnum `json:"factor,omitempty" url:"-"`
	// Optional. Allows a user who has previously enrolled in MFA to enroll with additional factors.<br />Note: Parameter can only be used with Universal Login; it cannot be used with Classic Login or custom MFA pages.
	AllowMultipleEnrollments *bool `json:"allow_multiple_enrollments,omitempty" url:"-"`
}
